version: "2"

run:
  relative-path-mode: gomod

issues:
  generated: lax

linters:
  default: standard
  enable:
    - bodyclose
    - sqlclosecheck

  settings:
    errcheck:
      check-blank: true
      check-type-assertions: true
