// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitegen

import (
	"database/sql"
)

type Delivery struct {
	ID          string        `json:"id"`
	Status      string        `json:"status"`
	ClaimToken  string        `json:"claim_token"`
	ClaimedBy   string        `json:"claimed_by"`
	ClaimedAt   int64         `json:"claimed_at"`
	ProcessedAt sql.NullInt64 `json:"processed_at"`
	SeenAt      int64         `json:"seen_at"`
	LastError   string        `json:"last_error"`
}

type Run struct {
	Seq         int64         `json:"seq"`
	ID          string        `json:"id"`
	TaskID      string        `json:"task_id"`
	Repo        string        `json:"repo"`
	Task        string        `json:"task"`
	BaseBranch  string        `json:"base_branch"`
	HeadBranch  string        `json:"head_branch"`
	Trigger     string        `json:"trigger"`
	Debug       bool          `json:"debug"`
	Status      string        `json:"status"`
	RunDir      string        `json:"run_dir"`
	IssueNumber int64         `json:"issue_number"`
	PrNumber    int64         `json:"pr_number"`
	PrUrl       string        `json:"pr_url"`
	HeadSha     string        `json:"head_sha"`
	Context     string        `json:"context"`
	Error       string        `json:"error"`
	CreatedAt   int64         `json:"created_at"`
	UpdatedAt   int64         `json:"updated_at"`
	StartedAt   sql.NullInt64 `json:"started_at"`
	CompletedAt sql.NullInt64 `json:"completed_at"`
}

type RunLease struct {
	RunID          string `json:"run_id"`
	OwnerID        string `json:"owner_id"`
	HeartbeatAt    int64  `json:"heartbeat_at"`
	LeaseExpiresAt int64  `json:"lease_expires_at"`
}

type Task struct {
	ID           string `json:"id"`
	Repo         string `json:"repo"`
	IssueNumber  int64  `json:"issue_number"`
	PrNumber     int64  `json:"pr_number"`
	Status       string `json:"status"`
	PendingInput bool   `json:"pending_input"`
	LastRunID    string `json:"last_run_id"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}
