// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlitegen

import (
	"database/sql"
)

type Delivery struct {
	ID          string        `json:"id"`
	Status      string        `json:"status"`
	ClaimToken  string        `json:"claim_token"`
	ClaimedBy   string        `json:"claimed_by"`
	ClaimedAt   int64         `json:"claimed_at"`
	ProcessedAt sql.NullInt64 `json:"processed_at"`
	SeenAt      int64         `json:"seen_at"`
	LastError   string        `json:"last_error"`
}

type Run struct {
	Seq          int64         `json:"seq"`
	ID           string        `json:"id"`
	TaskID       string        `json:"task_id"`
	Repo         string        `json:"repo"`
	Task         string        `json:"task"`
	AgentBackend string        `json:"agent_backend"`
	BaseBranch   string        `json:"base_branch"`
	HeadBranch   string        `json:"head_branch"`
	Trigger      string        `json:"trigger"`
	Debug        bool          `json:"debug"`
	Status       string        `json:"status"`
	RunDir       string        `json:"run_dir"`
	IssueNumber  int64         `json:"issue_number"`
	PrNumber     int64         `json:"pr_number"`
	PrUrl        string        `json:"pr_url"`
	PrStatus     string        `json:"pr_status"`
	HeadSha      string        `json:"head_sha"`
	Context      string        `json:"context"`
	Error        string        `json:"error"`
	CreatedAt    int64         `json:"created_at"`
	UpdatedAt    int64         `json:"updated_at"`
	StartedAt    sql.NullInt64 `json:"started_at"`
	CompletedAt  sql.NullInt64 `json:"completed_at"`
}

type RunCancel struct {
	RunID       string `json:"run_id"`
	Reason      string `json:"reason"`
	Source      string `json:"source"`
	RequestedAt int64  `json:"requested_at"`
}

type RunExecution struct {
	RunID          string `json:"run_id"`
	Backend        string `json:"backend"`
	ContainerName  string `json:"container_name"`
	ContainerID    string `json:"container_id"`
	Status         string `json:"status"`
	ExitCode       int64  `json:"exit_code"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
	LastObservedAt int64  `json:"last_observed_at"`
}

type RunLease struct {
	RunID          string `json:"run_id"`
	OwnerID        string `json:"owner_id"`
	HeartbeatAt    int64  `json:"heartbeat_at"`
	LeaseExpiresAt int64  `json:"lease_expires_at"`
}

type Task struct {
	ID           string `json:"id"`
	Repo         string `json:"repo"`
	AgentBackend string `json:"agent_backend"`
	IssueNumber  int64  `json:"issue_number"`
	PrNumber     int64  `json:"pr_number"`
	Status       string `json:"status"`
	LastRunID    string `json:"last_run_id"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

type TaskAgentSession struct {
	TaskID           string `json:"task_id"`
	AgentBackend     string `json:"agent_backend"`
	BackendSessionID string `json:"backend_session_id"`
	SessionKey       string `json:"session_key"`
	SessionRoot      string `json:"session_root"`
	LastRunID        string `json:"last_run_id"`
	CreatedAt        int64  `json:"created_at"`
	UpdatedAt        int64  `json:"updated_at"`
}
