// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitegen

import (
	"database/sql"
)

type ApiKey struct {
	ID         string        `json:"id"`
	UserID     string        `json:"user_id"`
	KeyHash    string        `json:"key_hash"`
	Label      string        `json:"label"`
	CreatedAt  int64         `json:"created_at"`
	LastUsedAt int64         `json:"last_used_at"`
	DisabledAt sql.NullInt64 `json:"disabled_at"`
}

type CodexCredential struct {
	ID                string         `json:"id"`
	OwnerUserID       sql.NullString `json:"owner_user_id"`
	Scope             string         `json:"scope"`
	AgentRuntime      string         `json:"agent_runtime"`
	EncryptedAuthBlob []byte         `json:"encrypted_auth_blob"`
	Weight            int64          `json:"weight"`
	Status            string         `json:"status"`
	CooldownUntil     sql.NullInt64  `json:"cooldown_until"`
	LastError         string         `json:"last_error"`
	CreatedAt         int64          `json:"created_at"`
	UpdatedAt         int64          `json:"updated_at"`
}

type CredentialLease struct {
	ID           string        `json:"id"`
	CredentialID string        `json:"credential_id"`
	RunID        string        `json:"run_id"`
	UserID       string        `json:"user_id"`
	Strategy     string        `json:"strategy"`
	AcquiredAt   int64         `json:"acquired_at"`
	ExpiresAt    int64         `json:"expires_at"`
	ReleasedAt   sql.NullInt64 `json:"released_at"`
}

type CredentialUsage struct {
	CredentialID string `json:"credential_id"`
	WindowStart  int64  `json:"window_start"`
	Tokens       int64  `json:"tokens"`
	Runs         int64  `json:"runs"`
}

type Delivery struct {
	ID          string        `json:"id"`
	Status      string        `json:"status"`
	ClaimToken  string        `json:"claim_token"`
	ClaimedBy   string        `json:"claimed_by"`
	ClaimedAt   int64         `json:"claimed_at"`
	ProcessedAt sql.NullInt64 `json:"processed_at"`
	SeenAt      int64         `json:"seen_at"`
	LastError   string        `json:"last_error"`
}

type Run struct {
	Seq             int64         `json:"seq"`
	ID              string        `json:"id"`
	TaskID          string        `json:"task_id"`
	Repo            string        `json:"repo"`
	Task            string        `json:"task"`
	AgentBackend    string        `json:"agent_backend"`
	BaseBranch      string        `json:"base_branch"`
	HeadBranch      string        `json:"head_branch"`
	Trigger         string        `json:"trigger"`
	Debug           bool          `json:"debug"`
	Status          string        `json:"status"`
	RunDir          string        `json:"run_dir"`
	IssueNumber     int64         `json:"issue_number"`
	PrNumber        int64         `json:"pr_number"`
	CreatedByUserID string        `json:"created_by_user_id"`
	CredentialID    string        `json:"credential_id"`
	PrUrl           string        `json:"pr_url"`
	PrStatus        string        `json:"pr_status"`
	HeadSha         string        `json:"head_sha"`
	Context         string        `json:"context"`
	Error           string        `json:"error"`
	StatusReason    string        `json:"status_reason"`
	CreatedAt       int64         `json:"created_at"`
	UpdatedAt       int64         `json:"updated_at"`
	StartedAt       sql.NullInt64 `json:"started_at"`
	CompletedAt     sql.NullInt64 `json:"completed_at"`
}

type RunCancel struct {
	RunID       string `json:"run_id"`
	Reason      string `json:"reason"`
	Source      string `json:"source"`
	RequestedAt int64  `json:"requested_at"`
}

type RunExecution struct {
	RunID          string `json:"run_id"`
	Backend        string `json:"backend"`
	ContainerName  string `json:"container_name"`
	ContainerID    string `json:"container_id"`
	Status         string `json:"status"`
	ExitCode       int64  `json:"exit_code"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
	LastObservedAt int64  `json:"last_observed_at"`
}

type RunLease struct {
	RunID          string `json:"run_id"`
	OwnerID        string `json:"owner_id"`
	HeartbeatAt    int64  `json:"heartbeat_at"`
	LeaseExpiresAt int64  `json:"lease_expires_at"`
}

type RunTokenUsage struct {
	RunID                 string        `json:"run_id"`
	Backend               string        `json:"backend"`
	Provider              string        `json:"provider"`
	Model                 string        `json:"model"`
	TotalTokens           int64         `json:"total_tokens"`
	InputTokens           sql.NullInt64 `json:"input_tokens"`
	OutputTokens          sql.NullInt64 `json:"output_tokens"`
	CachedInputTokens     sql.NullInt64 `json:"cached_input_tokens"`
	ReasoningOutputTokens sql.NullInt64 `json:"reasoning_output_tokens"`
	RawUsageJson          string        `json:"raw_usage_json"`
	CapturedAt            int64         `json:"captured_at"`
	CreatedAt             int64         `json:"created_at"`
	UpdatedAt             int64         `json:"updated_at"`
}

type SchedulerPause struct {
	Scope       string `json:"scope"`
	Reason      string `json:"reason"`
	PausedUntil int64  `json:"paused_until"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type Task struct {
	ID              string `json:"id"`
	Repo            string `json:"repo"`
	AgentBackend    string `json:"agent_backend"`
	IssueNumber     int64  `json:"issue_number"`
	PrNumber        int64  `json:"pr_number"`
	CreatedByUserID string `json:"created_by_user_id"`
	Status          string `json:"status"`
	LastRunID       string `json:"last_run_id"`
	CreatedAt       int64  `json:"created_at"`
	UpdatedAt       int64  `json:"updated_at"`
}

type TaskAgentSession struct {
	TaskID           string `json:"task_id"`
	AgentBackend     string `json:"agent_backend"`
	BackendSessionID string `json:"backend_session_id"`
	SessionKey       string `json:"session_key"`
	SessionRoot      string `json:"session_root"`
	LastRunID        string `json:"last_run_id"`
	CreatedAt        int64  `json:"created_at"`
	UpdatedAt        int64  `json:"updated_at"`
}

type User struct {
	ID            string `json:"id"`
	ExternalLogin string `json:"external_login"`
	Role          string `json:"role"`
	CreatedAt     int64  `json:"created_at"`
	UpdatedAt     int64  `json:"updated_at"`
}
