// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlitegen

import (
	"context"
	"database/sql"
)

const activeRunForTask = `-- name: ActiveRunForTask :one
SELECT seq, id, task_id, repo, task, base_branch, head_branch, trigger, debug, status, run_dir, issue_number, pr_number, pr_url, head_sha, context, error, created_at, updated_at, started_at, completed_at
FROM runs
WHERE task_id = ? AND status IN ('queued', 'running')
ORDER BY seq DESC
LIMIT 1
`

func (q *Queries) ActiveRunForTask(ctx context.Context, taskID string) (Run, error) {
	row := q.db.QueryRowContext(ctx, activeRunForTask, taskID)
	var i Run
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.TaskID,
		&i.Repo,
		&i.Task,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Trigger,
		&i.Debug,
		&i.Status,
		&i.RunDir,
		&i.IssueNumber,
		&i.PrNumber,
		&i.PrUrl,
		&i.HeadSha,
		&i.Context,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const cancelQueuedRuns = `-- name: CancelQueuedRuns :exec
UPDATE runs
SET status = 'canceled', error = ?, updated_at = ?, completed_at = ?
WHERE task_id = ? AND status = 'queued'
`

type CancelQueuedRunsParams struct {
	Error       string        `json:"error"`
	UpdatedAt   int64         `json:"updated_at"`
	CompletedAt sql.NullInt64 `json:"completed_at"`
	TaskID      string        `json:"task_id"`
}

func (q *Queries) CancelQueuedRuns(ctx context.Context, arg CancelQueuedRunsParams) error {
	_, err := q.db.ExecContext(ctx, cancelQueuedRuns,
		arg.Error,
		arg.UpdatedAt,
		arg.CompletedAt,
		arg.TaskID,
	)
	return err
}

const claimDelivery = `-- name: ClaimDelivery :one
INSERT INTO deliveries (
  id,
  status,
  claim_token,
  claimed_by,
  claimed_at,
  processed_at,
  seen_at,
  last_error
)
VALUES (
  ?1,
  'processing',
  ?2,
  ?3,
  ?4,
  NULL,
  ?5,
  ''
)
ON CONFLICT(id) DO UPDATE SET
  status = CASE
    WHEN deliveries.status = 'processed' THEN deliveries.status
    WHEN deliveries.status = 'processing' AND deliveries.claimed_at >= (excluded.claimed_at - 600000000000) THEN deliveries.status
    ELSE 'processing'
  END,
  claim_token = CASE
    WHEN deliveries.status = 'processed' THEN deliveries.claim_token
    WHEN deliveries.status = 'processing' AND deliveries.claimed_at >= (excluded.claimed_at - 600000000000) THEN deliveries.claim_token
    ELSE excluded.claim_token
  END,
  claimed_by = CASE
    WHEN deliveries.status = 'processed' THEN deliveries.claimed_by
    WHEN deliveries.status = 'processing' AND deliveries.claimed_at >= (excluded.claimed_at - 600000000000) THEN deliveries.claimed_by
    ELSE excluded.claimed_by
  END,
  claimed_at = CASE
    WHEN deliveries.status = 'processed' THEN deliveries.claimed_at
    WHEN deliveries.status = 'processing' AND deliveries.claimed_at >= (excluded.claimed_at - 600000000000) THEN deliveries.claimed_at
    ELSE excluded.claimed_at
  END,
  last_error = CASE
    WHEN deliveries.status = 'processed' THEN deliveries.last_error
    WHEN deliveries.status = 'processing' AND deliveries.claimed_at >= (excluded.claimed_at - 600000000000) THEN deliveries.last_error
    ELSE ''
  END
RETURNING status, claim_token
`

type ClaimDeliveryParams struct {
	ID         string `json:"id"`
	ClaimToken string `json:"claim_token"`
	ClaimedBy  string `json:"claimed_by"`
	ClaimedAt  int64  `json:"claimed_at"`
	SeenAt     int64  `json:"seen_at"`
}

type ClaimDeliveryRow struct {
	Status     string `json:"status"`
	ClaimToken string `json:"claim_token"`
}

func (q *Queries) ClaimDelivery(ctx context.Context, arg ClaimDeliveryParams) (ClaimDeliveryRow, error) {
	row := q.db.QueryRowContext(ctx, claimDelivery,
		arg.ID,
		arg.ClaimToken,
		arg.ClaimedBy,
		arg.ClaimedAt,
		arg.SeenAt,
	)
	var i ClaimDeliveryRow
	err := row.Scan(&i.Status, &i.ClaimToken)
	return i, err
}

const claimRunStart = `-- name: ClaimRunStart :execrows
UPDATE runs
SET status = 'running', error = '', updated_at = ?, started_at = ?
WHERE id = ?
  AND status = 'queued'
  AND NOT EXISTS (
    SELECT 1
    FROM runs AS other
    WHERE other.task_id = runs.task_id
      AND other.status = 'running'
      AND other.id <> runs.id
  )
`

type ClaimRunStartParams struct {
	UpdatedAt int64         `json:"updated_at"`
	StartedAt sql.NullInt64 `json:"started_at"`
	ID        string        `json:"id"`
}

func (q *Queries) ClaimRunStart(ctx context.Context, arg ClaimRunStartParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimRunStart, arg.UpdatedAt, arg.StartedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeDeliveryClaim = `-- name: CompleteDeliveryClaim :execrows
UPDATE deliveries
SET
  status = 'processed',
  claim_token = '',
  claimed_by = '',
  claimed_at = 0,
  processed_at = ?,
  seen_at = ?,
  last_error = ''
WHERE id = ? AND claim_token = ?
`

type CompleteDeliveryClaimParams struct {
	ProcessedAt sql.NullInt64 `json:"processed_at"`
	SeenAt      int64         `json:"seen_at"`
	ID          string        `json:"id"`
	ClaimToken  string        `json:"claim_token"`
}

func (q *Queries) CompleteDeliveryClaim(ctx context.Context, arg CompleteDeliveryClaimParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeDeliveryClaim,
		arg.ProcessedAt,
		arg.SeenAt,
		arg.ID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countDeliveries = `-- name: CountDeliveries :one
SELECT COUNT(*)
FROM deliveries
`

func (q *Queries) CountDeliveries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeliveries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldestDeliveries = `-- name: DeleteOldestDeliveries :exec
DELETE FROM deliveries
WHERE id IN (
  SELECT id
  FROM deliveries
  ORDER BY seen_at ASC
  LIMIT ?
)
`

func (q *Queries) DeleteOldestDeliveries(ctx context.Context, limit int64) error {
	_, err := q.db.ExecContext(ctx, deleteOldestDeliveries, limit)
	return err
}

const deleteRunLease = `-- name: DeleteRunLease :execrows
DELETE FROM run_leases
WHERE run_id = ?
`

func (q *Queries) DeleteRunLease(ctx context.Context, runID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRunLease, runID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deliverySeen = `-- name: DeliverySeen :one
SELECT EXISTS(SELECT 1 FROM deliveries WHERE id = ?)
`

func (q *Queries) DeliverySeen(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, deliverySeen, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const findTaskByPR = `-- name: FindTaskByPR :one
SELECT id, repo, issue_number, pr_number, status, pending_input, last_run_id, created_at, updated_at
FROM tasks
WHERE repo = ? AND pr_number = ?
`

type FindTaskByPRParams struct {
	Repo     string `json:"repo"`
	PrNumber int64  `json:"pr_number"`
}

func (q *Queries) FindTaskByPR(ctx context.Context, arg FindTaskByPRParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, findTaskByPR, arg.Repo, arg.PrNumber)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.IssueNumber,
		&i.PrNumber,
		&i.Status,
		&i.PendingInput,
		&i.LastRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT seq, id, task_id, repo, task, base_branch, head_branch, trigger, debug, status, run_dir, issue_number, pr_number, pr_url, head_sha, context, error, created_at, updated_at, started_at, completed_at
FROM runs
WHERE id = ?
`

func (q *Queries) GetRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.TaskID,
		&i.Repo,
		&i.Task,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Trigger,
		&i.Debug,
		&i.Status,
		&i.RunDir,
		&i.IssueNumber,
		&i.PrNumber,
		&i.PrUrl,
		&i.HeadSha,
		&i.Context,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRunLease = `-- name: GetRunLease :one
SELECT run_id, owner_id, heartbeat_at, lease_expires_at
FROM run_leases
WHERE run_id = ?
`

func (q *Queries) GetRunLease(ctx context.Context, runID string) (RunLease, error) {
	row := q.db.QueryRowContext(ctx, getRunLease, runID)
	var i RunLease
	err := row.Scan(
		&i.RunID,
		&i.OwnerID,
		&i.HeartbeatAt,
		&i.LeaseExpiresAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, repo, issue_number, pr_number, status, pending_input, last_run_id, created_at, updated_at
FROM tasks
WHERE id = ?
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.IssueNumber,
		&i.PrNumber,
		&i.Status,
		&i.PendingInput,
		&i.LastRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRun = `-- name: InsertRun :one
INSERT INTO runs (
  id,
  task_id,
  repo,
  task,
  base_branch,
  head_branch,
  trigger,
  debug,
  status,
  run_dir,
  issue_number,
  pr_number,
  pr_url,
  head_sha,
  context,
  error,
  created_at,
  updated_at,
  started_at,
  completed_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING seq, id, task_id, repo, task, base_branch, head_branch, trigger, debug, status, run_dir, issue_number, pr_number, pr_url, head_sha, context, error, created_at, updated_at, started_at, completed_at
`

type InsertRunParams struct {
	ID          string        `json:"id"`
	TaskID      string        `json:"task_id"`
	Repo        string        `json:"repo"`
	Task        string        `json:"task"`
	BaseBranch  string        `json:"base_branch"`
	HeadBranch  string        `json:"head_branch"`
	Trigger     string        `json:"trigger"`
	Debug       bool          `json:"debug"`
	Status      string        `json:"status"`
	RunDir      string        `json:"run_dir"`
	IssueNumber int64         `json:"issue_number"`
	PrNumber    int64         `json:"pr_number"`
	PrUrl       string        `json:"pr_url"`
	HeadSha     string        `json:"head_sha"`
	Context     string        `json:"context"`
	Error       string        `json:"error"`
	CreatedAt   int64         `json:"created_at"`
	UpdatedAt   int64         `json:"updated_at"`
	StartedAt   sql.NullInt64 `json:"started_at"`
	CompletedAt sql.NullInt64 `json:"completed_at"`
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, insertRun,
		arg.ID,
		arg.TaskID,
		arg.Repo,
		arg.Task,
		arg.BaseBranch,
		arg.HeadBranch,
		arg.Trigger,
		arg.Debug,
		arg.Status,
		arg.RunDir,
		arg.IssueNumber,
		arg.PrNumber,
		arg.PrUrl,
		arg.HeadSha,
		arg.Context,
		arg.Error,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i Run
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.TaskID,
		&i.Repo,
		&i.Task,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Trigger,
		&i.Debug,
		&i.Status,
		&i.RunDir,
		&i.IssueNumber,
		&i.PrNumber,
		&i.PrUrl,
		&i.HeadSha,
		&i.Context,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const isTaskCompleted = `-- name: IsTaskCompleted :one
SELECT status = 'completed'
FROM tasks
WHERE id = ?
`

func (q *Queries) IsTaskCompleted(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isTaskCompleted, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const lastRunForTask = `-- name: LastRunForTask :one
SELECT seq, id, task_id, repo, task, base_branch, head_branch, trigger, debug, status, run_dir, issue_number, pr_number, pr_url, head_sha, context, error, created_at, updated_at, started_at, completed_at
FROM runs
WHERE task_id = ?
ORDER BY seq DESC
LIMIT 1
`

func (q *Queries) LastRunForTask(ctx context.Context, taskID string) (Run, error) {
	row := q.db.QueryRowContext(ctx, lastRunForTask, taskID)
	var i Run
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.TaskID,
		&i.Repo,
		&i.Task,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Trigger,
		&i.Debug,
		&i.Status,
		&i.RunDir,
		&i.IssueNumber,
		&i.PrNumber,
		&i.PrUrl,
		&i.HeadSha,
		&i.Context,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listRuns = `-- name: ListRuns :many
SELECT seq, id, task_id, repo, task, base_branch, head_branch, trigger, debug, status, run_dir, issue_number, pr_number, pr_url, head_sha, context, error, created_at, updated_at, started_at, completed_at
FROM runs
ORDER BY seq DESC
LIMIT ?
`

func (q *Queries) ListRuns(ctx context.Context, limit int64) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.TaskID,
			&i.Repo,
			&i.Task,
			&i.BaseBranch,
			&i.HeadBranch,
			&i.Trigger,
			&i.Debug,
			&i.Status,
			&i.RunDir,
			&i.IssueNumber,
			&i.PrNumber,
			&i.PrUrl,
			&i.HeadSha,
			&i.Context,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskCompleted = `-- name: MarkTaskCompleted :execrows
UPDATE tasks
SET status = 'completed', pending_input = 0, updated_at = ?
WHERE id = ?
`

type MarkTaskCompletedParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) MarkTaskCompleted(ctx context.Context, arg MarkTaskCompletedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markTaskCompleted, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordDelivery = `-- name: RecordDelivery :exec
INSERT OR REPLACE INTO deliveries (
  id,
  status,
  claim_token,
  claimed_by,
  claimed_at,
  processed_at,
  seen_at,
  last_error
)
VALUES (?, 'processed', '', '', 0, ?, ?, '')
`

type RecordDeliveryParams struct {
	ID          string        `json:"id"`
	ProcessedAt sql.NullInt64 `json:"processed_at"`
	SeenAt      int64         `json:"seen_at"`
}

func (q *Queries) RecordDelivery(ctx context.Context, arg RecordDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, recordDelivery, arg.ID, arg.ProcessedAt, arg.SeenAt)
	return err
}

const releaseDeliveryClaim = `-- name: ReleaseDeliveryClaim :execrows
DELETE FROM deliveries
WHERE id = ? AND claim_token = ?
`

type ReleaseDeliveryClaimParams struct {
	ID         string `json:"id"`
	ClaimToken string `json:"claim_token"`
}

func (q *Queries) ReleaseDeliveryClaim(ctx context.Context, arg ReleaseDeliveryClaimParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseDeliveryClaim, arg.ID, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const renewRunLease = `-- name: RenewRunLease :execrows
UPDATE run_leases
SET
  heartbeat_at = ?,
  lease_expires_at = ?
WHERE run_id = ? AND owner_id = ?
`

type RenewRunLeaseParams struct {
	HeartbeatAt    int64  `json:"heartbeat_at"`
	LeaseExpiresAt int64  `json:"lease_expires_at"`
	RunID          string `json:"run_id"`
	OwnerID        string `json:"owner_id"`
}

func (q *Queries) RenewRunLease(ctx context.Context, arg RenewRunLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewRunLease,
		arg.HeartbeatAt,
		arg.LeaseExpiresAt,
		arg.RunID,
		arg.OwnerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTaskLastRun = `-- name: SetTaskLastRun :execrows
UPDATE tasks
SET
  last_run_id = ?1,
  updated_at = ?2,
  issue_number = CASE WHEN ?3 > 0 THEN ?3 ELSE issue_number END,
  pr_number = CASE WHEN ?4 > 0 THEN ?4 ELSE pr_number END
WHERE id = ?5
`

type SetTaskLastRunParams struct {
	LastRunID   string      `json:"last_run_id"`
	UpdatedAt   int64       `json:"updated_at"`
	IssueNumber interface{} `json:"issue_number"`
	PrNumber    interface{} `json:"pr_number"`
	ID          string      `json:"id"`
}

func (q *Queries) SetTaskLastRun(ctx context.Context, arg SetTaskLastRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTaskLastRun,
		arg.LastRunID,
		arg.UpdatedAt,
		arg.IssueNumber,
		arg.PrNumber,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTaskPR = `-- name: SetTaskPR :execrows
UPDATE tasks
SET pr_number = ?, updated_at = ?
WHERE id = ?
`

type SetTaskPRParams struct {
	PrNumber  int64  `json:"pr_number"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) SetTaskPR(ctx context.Context, arg SetTaskPRParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTaskPR, arg.PrNumber, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTaskPendingInput = `-- name: SetTaskPendingInput :execrows
UPDATE tasks
SET pending_input = ?, updated_at = ?
WHERE id = ?
`

type SetTaskPendingInputParams struct {
	PendingInput bool   `json:"pending_input"`
	UpdatedAt    int64  `json:"updated_at"`
	ID           string `json:"id"`
}

func (q *Queries) SetTaskPendingInput(ctx context.Context, arg SetTaskPendingInputParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTaskPendingInput, arg.PendingInput, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const trimOldRuns = `-- name: TrimOldRuns :exec
DELETE FROM runs
WHERE id IN (
  SELECT id
  FROM runs
  ORDER BY seq DESC
  LIMIT -1 OFFSET ?
)
`

func (q *Queries) TrimOldRuns(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, trimOldRuns, offset)
	return err
}

const updateRun = `-- name: UpdateRun :execrows
UPDATE runs
SET
  task_id = ?,
  repo = ?,
  task = ?,
  base_branch = ?,
  head_branch = ?,
  trigger = ?,
  debug = ?,
  status = ?,
  run_dir = ?,
  issue_number = ?,
  pr_number = ?,
  pr_url = ?,
  head_sha = ?,
  context = ?,
  error = ?,
  created_at = ?,
  updated_at = ?,
  started_at = ?,
  completed_at = ?
WHERE id = ?
`

type UpdateRunParams struct {
	TaskID      string        `json:"task_id"`
	Repo        string        `json:"repo"`
	Task        string        `json:"task"`
	BaseBranch  string        `json:"base_branch"`
	HeadBranch  string        `json:"head_branch"`
	Trigger     string        `json:"trigger"`
	Debug       bool          `json:"debug"`
	Status      string        `json:"status"`
	RunDir      string        `json:"run_dir"`
	IssueNumber int64         `json:"issue_number"`
	PrNumber    int64         `json:"pr_number"`
	PrUrl       string        `json:"pr_url"`
	HeadSha     string        `json:"head_sha"`
	Context     string        `json:"context"`
	Error       string        `json:"error"`
	CreatedAt   int64         `json:"created_at"`
	UpdatedAt   int64         `json:"updated_at"`
	StartedAt   sql.NullInt64 `json:"started_at"`
	CompletedAt sql.NullInt64 `json:"completed_at"`
	ID          string        `json:"id"`
}

func (q *Queries) UpdateRun(ctx context.Context, arg UpdateRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRun,
		arg.TaskID,
		arg.Repo,
		arg.Task,
		arg.BaseBranch,
		arg.HeadBranch,
		arg.Trigger,
		arg.Debug,
		arg.Status,
		arg.RunDir,
		arg.IssueNumber,
		arg.PrNumber,
		arg.PrUrl,
		arg.HeadSha,
		arg.Context,
		arg.Error,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertRunLease = `-- name: UpsertRunLease :exec
INSERT INTO run_leases (run_id, owner_id, heartbeat_at, lease_expires_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(run_id) DO UPDATE SET
  owner_id = excluded.owner_id,
  heartbeat_at = excluded.heartbeat_at,
  lease_expires_at = excluded.lease_expires_at
`

type UpsertRunLeaseParams struct {
	RunID          string `json:"run_id"`
	OwnerID        string `json:"owner_id"`
	HeartbeatAt    int64  `json:"heartbeat_at"`
	LeaseExpiresAt int64  `json:"lease_expires_at"`
}

func (q *Queries) UpsertRunLease(ctx context.Context, arg UpsertRunLeaseParams) error {
	_, err := q.db.ExecContext(ctx, upsertRunLease,
		arg.RunID,
		arg.OwnerID,
		arg.HeartbeatAt,
		arg.LeaseExpiresAt,
	)
	return err
}

const upsertTask = `-- name: UpsertTask :one
INSERT INTO tasks (
  id,
  repo,
  issue_number,
  pr_number,
  status,
  pending_input,
  last_run_id,
  created_at,
  updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  repo = excluded.repo,
  issue_number = CASE WHEN excluded.issue_number > 0 THEN excluded.issue_number ELSE tasks.issue_number END,
  pr_number = CASE WHEN excluded.pr_number > 0 THEN excluded.pr_number ELSE tasks.pr_number END,
  updated_at = excluded.updated_at
RETURNING id, repo, issue_number, pr_number, status, pending_input, last_run_id, created_at, updated_at
`

type UpsertTaskParams struct {
	ID           string `json:"id"`
	Repo         string `json:"repo"`
	IssueNumber  int64  `json:"issue_number"`
	PrNumber     int64  `json:"pr_number"`
	Status       string `json:"status"`
	PendingInput bool   `json:"pending_input"`
	LastRunID    string `json:"last_run_id"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) UpsertTask(ctx context.Context, arg UpsertTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, upsertTask,
		arg.ID,
		arg.Repo,
		arg.IssueNumber,
		arg.PrNumber,
		arg.Status,
		arg.PendingInput,
		arg.LastRunID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.IssueNumber,
		&i.PrNumber,
		&i.Status,
		&i.PendingInput,
		&i.LastRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
