// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlitegen

import (
	"context"
	"database/sql"
)

const activeRunForTask = `-- name: ActiveRunForTask :one
SELECT seq, id, task_id, repo, task, agent_backend, base_branch, head_branch, trigger, debug, status, run_dir, issue_number, pr_number, pr_url, pr_status, head_sha, context, error, created_at, updated_at, started_at, completed_at
FROM runs
WHERE task_id = ? AND status IN ('queued', 'running')
ORDER BY seq DESC
LIMIT 1
`

type ActiveRunForTaskRow struct {
	Seq          int64         `json:"seq"`
	ID           string        `json:"id"`
	TaskID       string        `json:"task_id"`
	Repo         string        `json:"repo"`
	Task         string        `json:"task"`
	AgentBackend string        `json:"agent_backend"`
	BaseBranch   string        `json:"base_branch"`
	HeadBranch   string        `json:"head_branch"`
	Trigger      string        `json:"trigger"`
	Debug        bool          `json:"debug"`
	Status       string        `json:"status"`
	RunDir       string        `json:"run_dir"`
	IssueNumber  int64         `json:"issue_number"`
	PrNumber     int64         `json:"pr_number"`
	PrUrl        string        `json:"pr_url"`
	PrStatus     string        `json:"pr_status"`
	HeadSha      string        `json:"head_sha"`
	Context      string        `json:"context"`
	Error        string        `json:"error"`
	CreatedAt    int64         `json:"created_at"`
	UpdatedAt    int64         `json:"updated_at"`
	StartedAt    sql.NullInt64 `json:"started_at"`
	CompletedAt  sql.NullInt64 `json:"completed_at"`
}

func (q *Queries) ActiveRunForTask(ctx context.Context, taskID string) (ActiveRunForTaskRow, error) {
	row := q.db.QueryRowContext(ctx, activeRunForTask, taskID)
	var i ActiveRunForTaskRow
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.TaskID,
		&i.Repo,
		&i.Task,
		&i.AgentBackend,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Trigger,
		&i.Debug,
		&i.Status,
		&i.RunDir,
		&i.IssueNumber,
		&i.PrNumber,
		&i.PrUrl,
		&i.PrStatus,
		&i.HeadSha,
		&i.Context,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const cancelQueuedRuns = `-- name: CancelQueuedRuns :exec
UPDATE runs
SET status = 'canceled', error = ?, updated_at = ?, completed_at = ?
WHERE task_id = ? AND status = 'queued'
`

type CancelQueuedRunsParams struct {
	Error       string        `json:"error"`
	UpdatedAt   int64         `json:"updated_at"`
	CompletedAt sql.NullInt64 `json:"completed_at"`
	TaskID      string        `json:"task_id"`
}

func (q *Queries) CancelQueuedRuns(ctx context.Context, arg CancelQueuedRunsParams) error {
	_, err := q.db.ExecContext(ctx, cancelQueuedRuns,
		arg.Error,
		arg.UpdatedAt,
		arg.CompletedAt,
		arg.TaskID,
	)
	return err
}

const claimDelivery = `-- name: ClaimDelivery :one
INSERT INTO deliveries (
  id,
  status,
  claim_token,
  claimed_by,
  claimed_at,
  processed_at,
  seen_at,
  last_error
)
VALUES (
  ?1,
  'processing',
  ?2,
  ?3,
  ?4,
  NULL,
  ?5,
  ''
)
ON CONFLICT(id) DO UPDATE SET
  status = CASE
    WHEN deliveries.status = 'processed' THEN deliveries.status
    WHEN deliveries.status = 'processing' AND deliveries.claimed_at >= (excluded.claimed_at - 600000000000) THEN deliveries.status
    ELSE 'processing'
  END,
  claim_token = CASE
    WHEN deliveries.status = 'processed' THEN deliveries.claim_token
    WHEN deliveries.status = 'processing' AND deliveries.claimed_at >= (excluded.claimed_at - 600000000000) THEN deliveries.claim_token
    ELSE excluded.claim_token
  END,
  claimed_by = CASE
    WHEN deliveries.status = 'processed' THEN deliveries.claimed_by
    WHEN deliveries.status = 'processing' AND deliveries.claimed_at >= (excluded.claimed_at - 600000000000) THEN deliveries.claimed_by
    ELSE excluded.claimed_by
  END,
  claimed_at = CASE
    WHEN deliveries.status = 'processed' THEN deliveries.claimed_at
    WHEN deliveries.status = 'processing' AND deliveries.claimed_at >= (excluded.claimed_at - 600000000000) THEN deliveries.claimed_at
    ELSE excluded.claimed_at
  END,
  last_error = CASE
    WHEN deliveries.status = 'processed' THEN deliveries.last_error
    WHEN deliveries.status = 'processing' AND deliveries.claimed_at >= (excluded.claimed_at - 600000000000) THEN deliveries.last_error
    ELSE ''
  END
RETURNING status, claim_token
`

type ClaimDeliveryParams struct {
	ID         string `json:"id"`
	ClaimToken string `json:"claim_token"`
	ClaimedBy  string `json:"claimed_by"`
	ClaimedAt  int64  `json:"claimed_at"`
	SeenAt     int64  `json:"seen_at"`
}

type ClaimDeliveryRow struct {
	Status     string `json:"status"`
	ClaimToken string `json:"claim_token"`
}

func (q *Queries) ClaimDelivery(ctx context.Context, arg ClaimDeliveryParams) (ClaimDeliveryRow, error) {
	row := q.db.QueryRowContext(ctx, claimDelivery,
		arg.ID,
		arg.ClaimToken,
		arg.ClaimedBy,
		arg.ClaimedAt,
		arg.SeenAt,
	)
	var i ClaimDeliveryRow
	err := row.Scan(&i.Status, &i.ClaimToken)
	return i, err
}

const claimNextQueuedRun = `-- name: ClaimNextQueuedRun :one
UPDATE runs
SET status = 'running', error = '', updated_at = ?1, started_at = ?2
WHERE id = (
  SELECT r.id
  FROM runs AS r
  WHERE r.status = 'queued'
    AND NOT EXISTS (
      SELECT 1
      FROM runs AS other
      WHERE other.task_id = r.task_id
        AND other.status = 'running'
    )
    AND NOT EXISTS (
      SELECT 1
      FROM run_cancels AS rc
      WHERE rc.run_id = r.id
    )
  ORDER BY r.created_at ASC, r.seq ASC
  LIMIT 1
)
  AND status = 'queued'
  AND NOT EXISTS (
    SELECT 1
    FROM runs AS other
    WHERE other.task_id = runs.task_id
      AND other.status = 'running'
      AND other.id <> runs.id
  )
RETURNING
  seq,
  id,
  task_id,
  repo,
  task,
  agent_backend,
  base_branch,
  head_branch,
  trigger,
  debug,
  status,
  run_dir,
  issue_number,
  pr_number,
  pr_url,
  pr_status,
  head_sha,
  context,
  error,
  created_at,
  updated_at,
  started_at,
  completed_at
`

type ClaimNextQueuedRunParams struct {
	UpdatedAt int64         `json:"updated_at"`
	StartedAt sql.NullInt64 `json:"started_at"`
}

type ClaimNextQueuedRunRow struct {
	Seq          int64         `json:"seq"`
	ID           string        `json:"id"`
	TaskID       string        `json:"task_id"`
	Repo         string        `json:"repo"`
	Task         string        `json:"task"`
	AgentBackend string        `json:"agent_backend"`
	BaseBranch   string        `json:"base_branch"`
	HeadBranch   string        `json:"head_branch"`
	Trigger      string        `json:"trigger"`
	Debug        bool          `json:"debug"`
	Status       string        `json:"status"`
	RunDir       string        `json:"run_dir"`
	IssueNumber  int64         `json:"issue_number"`
	PrNumber     int64         `json:"pr_number"`
	PrUrl        string        `json:"pr_url"`
	PrStatus     string        `json:"pr_status"`
	HeadSha      string        `json:"head_sha"`
	Context      string        `json:"context"`
	Error        string        `json:"error"`
	CreatedAt    int64         `json:"created_at"`
	UpdatedAt    int64         `json:"updated_at"`
	StartedAt    sql.NullInt64 `json:"started_at"`
	CompletedAt  sql.NullInt64 `json:"completed_at"`
}

func (q *Queries) ClaimNextQueuedRun(ctx context.Context, arg ClaimNextQueuedRunParams) (ClaimNextQueuedRunRow, error) {
	row := q.db.QueryRowContext(ctx, claimNextQueuedRun, arg.UpdatedAt, arg.StartedAt)
	var i ClaimNextQueuedRunRow
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.TaskID,
		&i.Repo,
		&i.Task,
		&i.AgentBackend,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Trigger,
		&i.Debug,
		&i.Status,
		&i.RunDir,
		&i.IssueNumber,
		&i.PrNumber,
		&i.PrUrl,
		&i.PrStatus,
		&i.HeadSha,
		&i.Context,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const claimNextQueuedRunForTask = `-- name: ClaimNextQueuedRunForTask :one
UPDATE runs
SET status = 'running', error = '', updated_at = ?1, started_at = ?2
WHERE id = (
  SELECT r.id
  FROM runs AS r
  WHERE r.status = 'queued'
    AND r.task_id = ?3
    AND NOT EXISTS (
      SELECT 1
      FROM runs AS other
      WHERE other.task_id = r.task_id
        AND other.status = 'running'
    )
    AND NOT EXISTS (
      SELECT 1
      FROM run_cancels AS rc
      WHERE rc.run_id = r.id
    )
  ORDER BY r.created_at ASC, r.seq ASC
  LIMIT 1
)
  AND status = 'queued'
  AND NOT EXISTS (
    SELECT 1
    FROM runs AS other
    WHERE other.task_id = runs.task_id
      AND other.status = 'running'
      AND other.id <> runs.id
  )
RETURNING
  seq,
  id,
  task_id,
  repo,
  task,
  agent_backend,
  base_branch,
  head_branch,
  trigger,
  debug,
  status,
  run_dir,
  issue_number,
  pr_number,
  pr_url,
  pr_status,
  head_sha,
  context,
  error,
  created_at,
  updated_at,
  started_at,
  completed_at
`

type ClaimNextQueuedRunForTaskParams struct {
	UpdatedAt int64         `json:"updated_at"`
	StartedAt sql.NullInt64 `json:"started_at"`
	TaskID    string        `json:"task_id"`
}

type ClaimNextQueuedRunForTaskRow struct {
	Seq          int64         `json:"seq"`
	ID           string        `json:"id"`
	TaskID       string        `json:"task_id"`
	Repo         string        `json:"repo"`
	Task         string        `json:"task"`
	AgentBackend string        `json:"agent_backend"`
	BaseBranch   string        `json:"base_branch"`
	HeadBranch   string        `json:"head_branch"`
	Trigger      string        `json:"trigger"`
	Debug        bool          `json:"debug"`
	Status       string        `json:"status"`
	RunDir       string        `json:"run_dir"`
	IssueNumber  int64         `json:"issue_number"`
	PrNumber     int64         `json:"pr_number"`
	PrUrl        string        `json:"pr_url"`
	PrStatus     string        `json:"pr_status"`
	HeadSha      string        `json:"head_sha"`
	Context      string        `json:"context"`
	Error        string        `json:"error"`
	CreatedAt    int64         `json:"created_at"`
	UpdatedAt    int64         `json:"updated_at"`
	StartedAt    sql.NullInt64 `json:"started_at"`
	CompletedAt  sql.NullInt64 `json:"completed_at"`
}

func (q *Queries) ClaimNextQueuedRunForTask(ctx context.Context, arg ClaimNextQueuedRunForTaskParams) (ClaimNextQueuedRunForTaskRow, error) {
	row := q.db.QueryRowContext(ctx, claimNextQueuedRunForTask, arg.UpdatedAt, arg.StartedAt, arg.TaskID)
	var i ClaimNextQueuedRunForTaskRow
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.TaskID,
		&i.Repo,
		&i.Task,
		&i.AgentBackend,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Trigger,
		&i.Debug,
		&i.Status,
		&i.RunDir,
		&i.IssueNumber,
		&i.PrNumber,
		&i.PrUrl,
		&i.PrStatus,
		&i.HeadSha,
		&i.Context,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const claimRunStart = `-- name: ClaimRunStart :execrows
UPDATE runs
SET status = 'running', error = '', updated_at = ?, started_at = ?
WHERE id = ?
  AND status = 'queued'
  AND NOT EXISTS (
    SELECT 1
    FROM runs AS other
    WHERE other.task_id = runs.task_id
      AND other.status = 'running'
      AND other.id <> runs.id
  )
`

type ClaimRunStartParams struct {
	UpdatedAt int64         `json:"updated_at"`
	StartedAt sql.NullInt64 `json:"started_at"`
	ID        string        `json:"id"`
}

func (q *Queries) ClaimRunStart(ctx context.Context, arg ClaimRunStartParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimRunStart, arg.UpdatedAt, arg.StartedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeDeliveryClaim = `-- name: CompleteDeliveryClaim :execrows
UPDATE deliveries
SET
  status = 'processed',
  claim_token = '',
  claimed_by = '',
  claimed_at = 0,
  processed_at = ?,
  seen_at = ?,
  last_error = ''
WHERE id = ? AND claim_token = ?
`

type CompleteDeliveryClaimParams struct {
	ProcessedAt sql.NullInt64 `json:"processed_at"`
	SeenAt      int64         `json:"seen_at"`
	ID          string        `json:"id"`
	ClaimToken  string        `json:"claim_token"`
}

func (q *Queries) CompleteDeliveryClaim(ctx context.Context, arg CompleteDeliveryClaimParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeDeliveryClaim,
		arg.ProcessedAt,
		arg.SeenAt,
		arg.ID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countDeliveries = `-- name: CountDeliveries :one
SELECT COUNT(*)
FROM deliveries
`

func (q *Queries) CountDeliveries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeliveries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRunLeasesByOwner = `-- name: CountRunLeasesByOwner :one
SELECT COUNT(*)
FROM run_leases
WHERE owner_id = ?
`

func (q *Queries) CountRunLeasesByOwner(ctx context.Context, ownerID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRunLeasesByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCodexCredential = `-- name: CreateCodexCredential :exec
INSERT INTO codex_credentials (
  id,
  owner_user_id,
  scope,
  encrypted_auth_blob,
  weight,
  status,
  cooldown_until,
  last_error,
  created_at,
  updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCodexCredentialParams struct {
	ID                string         `json:"id"`
	OwnerUserID       sql.NullString `json:"owner_user_id"`
	Scope             string         `json:"scope"`
	EncryptedAuthBlob []byte         `json:"encrypted_auth_blob"`
	Weight            int64          `json:"weight"`
	Status            string         `json:"status"`
	CooldownUntil     sql.NullInt64  `json:"cooldown_until"`
	LastError         string         `json:"last_error"`
	CreatedAt         int64          `json:"created_at"`
	UpdatedAt         int64          `json:"updated_at"`
}

func (q *Queries) CreateCodexCredential(ctx context.Context, arg CreateCodexCredentialParams) error {
	_, err := q.db.ExecContext(ctx, createCodexCredential,
		arg.ID,
		arg.OwnerUserID,
		arg.Scope,
		arg.EncryptedAuthBlob,
		arg.Weight,
		arg.Status,
		arg.CooldownUntil,
		arg.LastError,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteOldestDeliveries = `-- name: DeleteOldestDeliveries :exec
DELETE FROM deliveries
WHERE id IN (
  SELECT id
  FROM deliveries
  ORDER BY seen_at ASC
  LIMIT ?
)
`

func (q *Queries) DeleteOldestDeliveries(ctx context.Context, limit int64) error {
	_, err := q.db.ExecContext(ctx, deleteOldestDeliveries, limit)
	return err
}

const deleteRunCancel = `-- name: DeleteRunCancel :execrows
DELETE FROM run_cancels
WHERE run_id = ?
`

func (q *Queries) DeleteRunCancel(ctx context.Context, runID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRunCancel, runID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRunExecution = `-- name: DeleteRunExecution :execrows
DELETE FROM run_executions
WHERE run_id = ?
`

func (q *Queries) DeleteRunExecution(ctx context.Context, runID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRunExecution, runID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRunLease = `-- name: DeleteRunLease :execrows
DELETE FROM run_leases
WHERE run_id = ?
`

func (q *Queries) DeleteRunLease(ctx context.Context, runID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRunLease, runID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRunLeaseForOwner = `-- name: DeleteRunLeaseForOwner :execrows
DELETE FROM run_leases
WHERE run_id = ? AND owner_id = ?
`

type DeleteRunLeaseForOwnerParams struct {
	RunID   string `json:"run_id"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) DeleteRunLeaseForOwner(ctx context.Context, arg DeleteRunLeaseForOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRunLeaseForOwner, arg.RunID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTaskAgentSession = `-- name: DeleteTaskAgentSession :execrows
DELETE FROM task_agent_sessions
WHERE task_id = ?
`

func (q *Queries) DeleteTaskAgentSession(ctx context.Context, taskID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTaskAgentSession, taskID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deliverySeen = `-- name: DeliverySeen :one
SELECT EXISTS(SELECT 1 FROM deliveries WHERE id = ?)
`

func (q *Queries) DeliverySeen(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, deliverySeen, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const findTaskByPR = `-- name: FindTaskByPR :one
SELECT
  tasks.id,
  tasks.repo,
  tasks.agent_backend,
  tasks.issue_number,
  tasks.pr_number,
  tasks.status,
  EXISTS(
    SELECT 1
    FROM runs
    WHERE runs.task_id = tasks.id
      AND runs.status = 'queued'
  ) AS pending_input,
  tasks.last_run_id,
  tasks.created_at,
  tasks.updated_at
FROM tasks
WHERE tasks.repo = ? AND tasks.pr_number = ?
`

type FindTaskByPRParams struct {
	Repo     string `json:"repo"`
	PrNumber int64  `json:"pr_number"`
}

type FindTaskByPRRow struct {
	ID           string `json:"id"`
	Repo         string `json:"repo"`
	AgentBackend string `json:"agent_backend"`
	IssueNumber  int64  `json:"issue_number"`
	PrNumber     int64  `json:"pr_number"`
	Status       string `json:"status"`
	PendingInput int64  `json:"pending_input"`
	LastRunID    string `json:"last_run_id"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) FindTaskByPR(ctx context.Context, arg FindTaskByPRParams) (FindTaskByPRRow, error) {
	row := q.db.QueryRowContext(ctx, findTaskByPR, arg.Repo, arg.PrNumber)
	var i FindTaskByPRRow
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.AgentBackend,
		&i.IssueNumber,
		&i.PrNumber,
		&i.Status,
		&i.PendingInput,
		&i.LastRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIKeyPrincipal = `-- name: GetAPIKeyPrincipal :one
SELECT
  api_keys.id AS api_key_id,
  api_keys.user_id,
  users.external_login,
  users.role
FROM api_keys
JOIN users ON users.id = api_keys.user_id
WHERE api_keys.key_hash = ?
  AND api_keys.disabled_at IS NULL
`

type GetAPIKeyPrincipalRow struct {
	ApiKeyID      string `json:"api_key_id"`
	UserID        string `json:"user_id"`
	ExternalLogin string `json:"external_login"`
	Role          string `json:"role"`
}

func (q *Queries) GetAPIKeyPrincipal(ctx context.Context, keyHash string) (GetAPIKeyPrincipalRow, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyPrincipal, keyHash)
	var i GetAPIKeyPrincipalRow
	err := row.Scan(
		&i.ApiKeyID,
		&i.UserID,
		&i.ExternalLogin,
		&i.Role,
	)
	return i, err
}

const getActiveCredentialLeaseByRunID = `-- name: GetActiveCredentialLeaseByRunID :one
SELECT id, credential_id, run_id, user_id, strategy, acquired_at, expires_at, released_at
FROM credential_leases
WHERE run_id = ?
  AND released_at IS NULL
ORDER BY acquired_at DESC
LIMIT 1
`

func (q *Queries) GetActiveCredentialLeaseByRunID(ctx context.Context, runID string) (CredentialLease, error) {
	row := q.db.QueryRowContext(ctx, getActiveCredentialLeaseByRunID, runID)
	var i CredentialLease
	err := row.Scan(
		&i.ID,
		&i.CredentialID,
		&i.RunID,
		&i.UserID,
		&i.Strategy,
		&i.AcquiredAt,
		&i.ExpiresAt,
		&i.ReleasedAt,
	)
	return i, err
}

const getActiveSchedulerPause = `-- name: GetActiveSchedulerPause :one
SELECT
  scope,
  reason,
  paused_until,
  created_at,
  updated_at
FROM scheduler_pauses
WHERE scope = ?
  AND paused_until > ?
`

type GetActiveSchedulerPauseParams struct {
	Scope       string `json:"scope"`
	PausedUntil int64  `json:"paused_until"`
}

func (q *Queries) GetActiveSchedulerPause(ctx context.Context, arg GetActiveSchedulerPauseParams) (SchedulerPause, error) {
	row := q.db.QueryRowContext(ctx, getActiveSchedulerPause, arg.Scope, arg.PausedUntil)
	var i SchedulerPause
	err := row.Scan(
		&i.Scope,
		&i.Reason,
		&i.PausedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCodexCredential = `-- name: GetCodexCredential :one
SELECT
  id,
  owner_user_id,
  scope,
  encrypted_auth_blob,
  weight,
  status,
  cooldown_until,
  last_error,
  created_at,
  updated_at
FROM codex_credentials
WHERE id = ?
`

func (q *Queries) GetCodexCredential(ctx context.Context, id string) (CodexCredential, error) {
	row := q.db.QueryRowContext(ctx, getCodexCredential, id)
	var i CodexCredential
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Scope,
		&i.EncryptedAuthBlob,
		&i.Weight,
		&i.Status,
		&i.CooldownUntil,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredentialLease = `-- name: GetCredentialLease :one
SELECT id, credential_id, run_id, user_id, strategy, acquired_at, expires_at, released_at
FROM credential_leases
WHERE id = ?
`

func (q *Queries) GetCredentialLease(ctx context.Context, id string) (CredentialLease, error) {
	row := q.db.QueryRowContext(ctx, getCredentialLease, id)
	var i CredentialLease
	err := row.Scan(
		&i.ID,
		&i.CredentialID,
		&i.RunID,
		&i.UserID,
		&i.Strategy,
		&i.AcquiredAt,
		&i.ExpiresAt,
		&i.ReleasedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT seq, id, task_id, repo, task, agent_backend, base_branch, head_branch, trigger, debug, status, run_dir, issue_number, pr_number, pr_url, pr_status, head_sha, context, error, created_at, updated_at, started_at, completed_at
FROM runs
WHERE id = ?
`

type GetRunRow struct {
	Seq          int64         `json:"seq"`
	ID           string        `json:"id"`
	TaskID       string        `json:"task_id"`
	Repo         string        `json:"repo"`
	Task         string        `json:"task"`
	AgentBackend string        `json:"agent_backend"`
	BaseBranch   string        `json:"base_branch"`
	HeadBranch   string        `json:"head_branch"`
	Trigger      string        `json:"trigger"`
	Debug        bool          `json:"debug"`
	Status       string        `json:"status"`
	RunDir       string        `json:"run_dir"`
	IssueNumber  int64         `json:"issue_number"`
	PrNumber     int64         `json:"pr_number"`
	PrUrl        string        `json:"pr_url"`
	PrStatus     string        `json:"pr_status"`
	HeadSha      string        `json:"head_sha"`
	Context      string        `json:"context"`
	Error        string        `json:"error"`
	CreatedAt    int64         `json:"created_at"`
	UpdatedAt    int64         `json:"updated_at"`
	StartedAt    sql.NullInt64 `json:"started_at"`
	CompletedAt  sql.NullInt64 `json:"completed_at"`
}

func (q *Queries) GetRun(ctx context.Context, id string) (GetRunRow, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i GetRunRow
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.TaskID,
		&i.Repo,
		&i.Task,
		&i.AgentBackend,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Trigger,
		&i.Debug,
		&i.Status,
		&i.RunDir,
		&i.IssueNumber,
		&i.PrNumber,
		&i.PrUrl,
		&i.PrStatus,
		&i.HeadSha,
		&i.Context,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRunCancel = `-- name: GetRunCancel :one
SELECT run_id, reason, source, requested_at
FROM run_cancels
WHERE run_id = ?
`

func (q *Queries) GetRunCancel(ctx context.Context, runID string) (RunCancel, error) {
	row := q.db.QueryRowContext(ctx, getRunCancel, runID)
	var i RunCancel
	err := row.Scan(
		&i.RunID,
		&i.Reason,
		&i.Source,
		&i.RequestedAt,
	)
	return i, err
}

const getRunCredentialInfo = `-- name: GetRunCredentialInfo :one
SELECT id, created_by_user_id, credential_id
FROM runs
WHERE id = ?
`

type GetRunCredentialInfoRow struct {
	ID              string `json:"id"`
	CreatedByUserID string `json:"created_by_user_id"`
	CredentialID    string `json:"credential_id"`
}

func (q *Queries) GetRunCredentialInfo(ctx context.Context, id string) (GetRunCredentialInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getRunCredentialInfo, id)
	var i GetRunCredentialInfoRow
	err := row.Scan(&i.ID, &i.CreatedByUserID, &i.CredentialID)
	return i, err
}

const getRunExecution = `-- name: GetRunExecution :one
SELECT run_id, backend, container_name, container_id, status, exit_code, created_at, updated_at, last_observed_at
FROM run_executions
WHERE run_id = ?
`

func (q *Queries) GetRunExecution(ctx context.Context, runID string) (RunExecution, error) {
	row := q.db.QueryRowContext(ctx, getRunExecution, runID)
	var i RunExecution
	err := row.Scan(
		&i.RunID,
		&i.Backend,
		&i.ContainerName,
		&i.ContainerID,
		&i.Status,
		&i.ExitCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastObservedAt,
	)
	return i, err
}

const getRunLease = `-- name: GetRunLease :one
SELECT run_id, owner_id, heartbeat_at, lease_expires_at
FROM run_leases
WHERE run_id = ?
`

func (q *Queries) GetRunLease(ctx context.Context, runID string) (RunLease, error) {
	row := q.db.QueryRowContext(ctx, getRunLease, runID)
	var i RunLease
	err := row.Scan(
		&i.RunID,
		&i.OwnerID,
		&i.HeartbeatAt,
		&i.LeaseExpiresAt,
	)
	return i, err
}

const getRunLineage = `-- name: GetRunLineage :one
SELECT
  run_id,
  parent_pipeline_id,
  phase_name,
  phase_order,
  child_index,
  created_at
FROM run_lineage
WHERE run_id = ?
`

func (q *Queries) GetRunLineage(ctx context.Context, runID string) (RunLineage, error) {
	row := q.db.QueryRowContext(ctx, getRunLineage, runID)
	var i RunLineage
	err := row.Scan(
		&i.RunID,
		&i.ParentPipelineID,
		&i.PhaseName,
		&i.PhaseOrder,
		&i.ChildIndex,
		&i.CreatedAt,
	)
	return i, err
}

const getRunPipeline = `-- name: GetRunPipeline :one
SELECT
  id,
  task_id,
  repo,
  task,
  base_branch,
  head_branch,
  trigger,
  issue_number,
  pr_number,
  context,
  debug,
  created_by_user_id,
  artifact_dir,
  status,
  active_phase,
  failed_phase,
  cancel_requested,
  max_phases,
  max_child_runs_per_phase,
  total_child_runs,
  token_budget_total,
  token_budget_used,
  deadline_at,
  created_at,
  updated_at,
  completed_at
FROM run_pipelines
WHERE id = ?
`

func (q *Queries) GetRunPipeline(ctx context.Context, id string) (RunPipeline, error) {
	row := q.db.QueryRowContext(ctx, getRunPipeline, id)
	var i RunPipeline
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Repo,
		&i.Task,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Trigger,
		&i.IssueNumber,
		&i.PrNumber,
		&i.Context,
		&i.Debug,
		&i.CreatedByUserID,
		&i.ArtifactDir,
		&i.Status,
		&i.ActivePhase,
		&i.FailedPhase,
		&i.CancelRequested,
		&i.MaxPhases,
		&i.MaxChildRunsPerPhase,
		&i.TotalChildRuns,
		&i.TokenBudgetTotal,
		&i.TokenBudgetUsed,
		&i.DeadlineAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRunPipelineByTask = `-- name: GetRunPipelineByTask :one
SELECT
  id,
  task_id,
  repo,
  task,
  base_branch,
  head_branch,
  trigger,
  issue_number,
  pr_number,
  context,
  debug,
  created_by_user_id,
  artifact_dir,
  status,
  active_phase,
  failed_phase,
  cancel_requested,
  max_phases,
  max_child_runs_per_phase,
  total_child_runs,
  token_budget_total,
  token_budget_used,
  deadline_at,
  created_at,
  updated_at,
  completed_at
FROM run_pipelines
WHERE task_id = ?
`

func (q *Queries) GetRunPipelineByTask(ctx context.Context, taskID string) (RunPipeline, error) {
	row := q.db.QueryRowContext(ctx, getRunPipelineByTask, taskID)
	var i RunPipeline
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Repo,
		&i.Task,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Trigger,
		&i.IssueNumber,
		&i.PrNumber,
		&i.Context,
		&i.Debug,
		&i.CreatedByUserID,
		&i.ArtifactDir,
		&i.Status,
		&i.ActivePhase,
		&i.FailedPhase,
		&i.CancelRequested,
		&i.MaxPhases,
		&i.MaxChildRunsPerPhase,
		&i.TotalChildRuns,
		&i.TokenBudgetTotal,
		&i.TokenBudgetUsed,
		&i.DeadlineAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRunPipelinePhase = `-- name: GetRunPipelinePhase :one
SELECT
  pipeline_id,
  phase_name,
  phase_order,
  enabled,
  state,
  run_id,
  child_index,
  artifact_paths,
  error,
  created_at,
  updated_at,
  started_at,
  completed_at
FROM run_pipeline_phases
WHERE pipeline_id = ? AND phase_name = ?
`

type GetRunPipelinePhaseParams struct {
	PipelineID string `json:"pipeline_id"`
	PhaseName  string `json:"phase_name"`
}

func (q *Queries) GetRunPipelinePhase(ctx context.Context, arg GetRunPipelinePhaseParams) (RunPipelinePhase, error) {
	row := q.db.QueryRowContext(ctx, getRunPipelinePhase, arg.PipelineID, arg.PhaseName)
	var i RunPipelinePhase
	err := row.Scan(
		&i.PipelineID,
		&i.PhaseName,
		&i.PhaseOrder,
		&i.Enabled,
		&i.State,
		&i.RunID,
		&i.ChildIndex,
		&i.ArtifactPaths,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRunTokenUsage = `-- name: GetRunTokenUsage :one
SELECT
  run_id,
  backend,
  provider,
  model,
  total_tokens,
  input_tokens,
  output_tokens,
  cached_input_tokens,
  reasoning_output_tokens,
  raw_usage_json,
  captured_at,
  created_at,
  updated_at
FROM run_token_usage
WHERE run_id = ?
`

func (q *Queries) GetRunTokenUsage(ctx context.Context, runID string) (RunTokenUsage, error) {
	row := q.db.QueryRowContext(ctx, getRunTokenUsage, runID)
	var i RunTokenUsage
	err := row.Scan(
		&i.RunID,
		&i.Backend,
		&i.Provider,
		&i.Model,
		&i.TotalTokens,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedInputTokens,
		&i.ReasoningOutputTokens,
		&i.RawUsageJson,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT
  tasks.id,
  tasks.repo,
  tasks.agent_backend,
  tasks.issue_number,
  tasks.pr_number,
  tasks.status,
  EXISTS(
    SELECT 1
    FROM runs
    WHERE runs.task_id = tasks.id
      AND runs.status = 'queued'
  ) AS pending_input,
  tasks.last_run_id,
  tasks.created_at,
  tasks.updated_at
FROM tasks
WHERE tasks.id = ?
`

type GetTaskRow struct {
	ID           string `json:"id"`
	Repo         string `json:"repo"`
	AgentBackend string `json:"agent_backend"`
	IssueNumber  int64  `json:"issue_number"`
	PrNumber     int64  `json:"pr_number"`
	Status       string `json:"status"`
	PendingInput int64  `json:"pending_input"`
	LastRunID    string `json:"last_run_id"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) GetTask(ctx context.Context, id string) (GetTaskRow, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i GetTaskRow
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.AgentBackend,
		&i.IssueNumber,
		&i.PrNumber,
		&i.Status,
		&i.PendingInput,
		&i.LastRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskAgentSession = `-- name: GetTaskAgentSession :one
SELECT
  task_id,
  agent_backend,
  backend_session_id,
  session_key,
  session_root,
  last_run_id,
  created_at,
  updated_at
FROM task_agent_sessions
WHERE task_id = ?
`

func (q *Queries) GetTaskAgentSession(ctx context.Context, taskID string) (TaskAgentSession, error) {
	row := q.db.QueryRowContext(ctx, getTaskAgentSession, taskID)
	var i TaskAgentSession
	err := row.Scan(
		&i.TaskID,
		&i.AgentBackend,
		&i.BackendSessionID,
		&i.SessionKey,
		&i.SessionRoot,
		&i.LastRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByExternalLogin = `-- name: GetUserByExternalLogin :one
SELECT id, external_login, role, created_at, updated_at
FROM users
WHERE external_login = ?
`

func (q *Queries) GetUserByExternalLogin(ctx context.Context, externalLogin string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByExternalLogin, externalLogin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalLogin,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, external_login, role, created_at, updated_at
FROM users
WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalLogin,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRun = `-- name: InsertRun :one
INSERT INTO runs (
  id,
  task_id,
  repo,
  task,
  agent_backend,
  base_branch,
  head_branch,
  trigger,
  debug,
  status,
  run_dir,
  issue_number,
  pr_number,
  pr_url,
  pr_status,
  head_sha,
  context,
  error,
  created_at,
  updated_at,
  started_at,
  completed_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING seq, id, task_id, repo, task, agent_backend, base_branch, head_branch, trigger, debug, status, run_dir, issue_number, pr_number, pr_url, pr_status, head_sha, context, error, created_at, updated_at, started_at, completed_at
`

type InsertRunParams struct {
	ID           string        `json:"id"`
	TaskID       string        `json:"task_id"`
	Repo         string        `json:"repo"`
	Task         string        `json:"task"`
	AgentBackend string        `json:"agent_backend"`
	BaseBranch   string        `json:"base_branch"`
	HeadBranch   string        `json:"head_branch"`
	Trigger      string        `json:"trigger"`
	Debug        bool          `json:"debug"`
	Status       string        `json:"status"`
	RunDir       string        `json:"run_dir"`
	IssueNumber  int64         `json:"issue_number"`
	PrNumber     int64         `json:"pr_number"`
	PrUrl        string        `json:"pr_url"`
	PrStatus     string        `json:"pr_status"`
	HeadSha      string        `json:"head_sha"`
	Context      string        `json:"context"`
	Error        string        `json:"error"`
	CreatedAt    int64         `json:"created_at"`
	UpdatedAt    int64         `json:"updated_at"`
	StartedAt    sql.NullInt64 `json:"started_at"`
	CompletedAt  sql.NullInt64 `json:"completed_at"`
}

type InsertRunRow struct {
	Seq          int64         `json:"seq"`
	ID           string        `json:"id"`
	TaskID       string        `json:"task_id"`
	Repo         string        `json:"repo"`
	Task         string        `json:"task"`
	AgentBackend string        `json:"agent_backend"`
	BaseBranch   string        `json:"base_branch"`
	HeadBranch   string        `json:"head_branch"`
	Trigger      string        `json:"trigger"`
	Debug        bool          `json:"debug"`
	Status       string        `json:"status"`
	RunDir       string        `json:"run_dir"`
	IssueNumber  int64         `json:"issue_number"`
	PrNumber     int64         `json:"pr_number"`
	PrUrl        string        `json:"pr_url"`
	PrStatus     string        `json:"pr_status"`
	HeadSha      string        `json:"head_sha"`
	Context      string        `json:"context"`
	Error        string        `json:"error"`
	CreatedAt    int64         `json:"created_at"`
	UpdatedAt    int64         `json:"updated_at"`
	StartedAt    sql.NullInt64 `json:"started_at"`
	CompletedAt  sql.NullInt64 `json:"completed_at"`
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) (InsertRunRow, error) {
	row := q.db.QueryRowContext(ctx, insertRun,
		arg.ID,
		arg.TaskID,
		arg.Repo,
		arg.Task,
		arg.AgentBackend,
		arg.BaseBranch,
		arg.HeadBranch,
		arg.Trigger,
		arg.Debug,
		arg.Status,
		arg.RunDir,
		arg.IssueNumber,
		arg.PrNumber,
		arg.PrUrl,
		arg.PrStatus,
		arg.HeadSha,
		arg.Context,
		arg.Error,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i InsertRunRow
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.TaskID,
		&i.Repo,
		&i.Task,
		&i.AgentBackend,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Trigger,
		&i.Debug,
		&i.Status,
		&i.RunDir,
		&i.IssueNumber,
		&i.PrNumber,
		&i.PrUrl,
		&i.PrStatus,
		&i.HeadSha,
		&i.Context,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertRunLineage = `-- name: InsertRunLineage :exec
INSERT INTO run_lineage (
  run_id,
  parent_pipeline_id,
  phase_name,
  phase_order,
  child_index,
  created_at
)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertRunLineageParams struct {
	RunID            string `json:"run_id"`
	ParentPipelineID string `json:"parent_pipeline_id"`
	PhaseName        string `json:"phase_name"`
	PhaseOrder       int64  `json:"phase_order"`
	ChildIndex       int64  `json:"child_index"`
	CreatedAt        int64  `json:"created_at"`
}

func (q *Queries) InsertRunLineage(ctx context.Context, arg InsertRunLineageParams) error {
	_, err := q.db.ExecContext(ctx, insertRunLineage,
		arg.RunID,
		arg.ParentPipelineID,
		arg.PhaseName,
		arg.PhaseOrder,
		arg.ChildIndex,
		arg.CreatedAt,
	)
	return err
}

const insertRunPipeline = `-- name: InsertRunPipeline :one
INSERT INTO run_pipelines (
  id,
  task_id,
  repo,
  task,
  base_branch,
  head_branch,
  trigger,
  issue_number,
  pr_number,
  context,
  debug,
  created_by_user_id,
  artifact_dir,
  status,
  active_phase,
  failed_phase,
  cancel_requested,
  max_phases,
  max_child_runs_per_phase,
  total_child_runs,
  token_budget_total,
  token_budget_used,
  deadline_at,
  created_at,
  updated_at,
  completed_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING
  id,
  task_id,
  repo,
  task,
  base_branch,
  head_branch,
  trigger,
  issue_number,
  pr_number,
  context,
  debug,
  created_by_user_id,
  artifact_dir,
  status,
  active_phase,
  failed_phase,
  cancel_requested,
  max_phases,
  max_child_runs_per_phase,
  total_child_runs,
  token_budget_total,
  token_budget_used,
  deadline_at,
  created_at,
  updated_at,
  completed_at
`

type InsertRunPipelineParams struct {
	ID                   string        `json:"id"`
	TaskID               string        `json:"task_id"`
	Repo                 string        `json:"repo"`
	Task                 string        `json:"task"`
	BaseBranch           string        `json:"base_branch"`
	HeadBranch           string        `json:"head_branch"`
	Trigger              string        `json:"trigger"`
	IssueNumber          int64         `json:"issue_number"`
	PrNumber             int64         `json:"pr_number"`
	Context              string        `json:"context"`
	Debug                bool          `json:"debug"`
	CreatedByUserID      string        `json:"created_by_user_id"`
	ArtifactDir          string        `json:"artifact_dir"`
	Status               string        `json:"status"`
	ActivePhase          string        `json:"active_phase"`
	FailedPhase          string        `json:"failed_phase"`
	CancelRequested      bool          `json:"cancel_requested"`
	MaxPhases            int64         `json:"max_phases"`
	MaxChildRunsPerPhase int64         `json:"max_child_runs_per_phase"`
	TotalChildRuns       int64         `json:"total_child_runs"`
	TokenBudgetTotal     int64         `json:"token_budget_total"`
	TokenBudgetUsed      int64         `json:"token_budget_used"`
	DeadlineAt           sql.NullInt64 `json:"deadline_at"`
	CreatedAt            int64         `json:"created_at"`
	UpdatedAt            int64         `json:"updated_at"`
	CompletedAt          sql.NullInt64 `json:"completed_at"`
}

func (q *Queries) InsertRunPipeline(ctx context.Context, arg InsertRunPipelineParams) (RunPipeline, error) {
	row := q.db.QueryRowContext(ctx, insertRunPipeline,
		arg.ID,
		arg.TaskID,
		arg.Repo,
		arg.Task,
		arg.BaseBranch,
		arg.HeadBranch,
		arg.Trigger,
		arg.IssueNumber,
		arg.PrNumber,
		arg.Context,
		arg.Debug,
		arg.CreatedByUserID,
		arg.ArtifactDir,
		arg.Status,
		arg.ActivePhase,
		arg.FailedPhase,
		arg.CancelRequested,
		arg.MaxPhases,
		arg.MaxChildRunsPerPhase,
		arg.TotalChildRuns,
		arg.TokenBudgetTotal,
		arg.TokenBudgetUsed,
		arg.DeadlineAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CompletedAt,
	)
	var i RunPipeline
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Repo,
		&i.Task,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Trigger,
		&i.IssueNumber,
		&i.PrNumber,
		&i.Context,
		&i.Debug,
		&i.CreatedByUserID,
		&i.ArtifactDir,
		&i.Status,
		&i.ActivePhase,
		&i.FailedPhase,
		&i.CancelRequested,
		&i.MaxPhases,
		&i.MaxChildRunsPerPhase,
		&i.TotalChildRuns,
		&i.TokenBudgetTotal,
		&i.TokenBudgetUsed,
		&i.DeadlineAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertRunPipelinePhase = `-- name: InsertRunPipelinePhase :one
INSERT INTO run_pipeline_phases (
  pipeline_id,
  phase_name,
  phase_order,
  enabled,
  state,
  run_id,
  child_index,
  artifact_paths,
  error,
  created_at,
  updated_at,
  started_at,
  completed_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING
  pipeline_id,
  phase_name,
  phase_order,
  enabled,
  state,
  run_id,
  child_index,
  artifact_paths,
  error,
  created_at,
  updated_at,
  started_at,
  completed_at
`

type InsertRunPipelinePhaseParams struct {
	PipelineID    string        `json:"pipeline_id"`
	PhaseName     string        `json:"phase_name"`
	PhaseOrder    int64         `json:"phase_order"`
	Enabled       bool          `json:"enabled"`
	State         string        `json:"state"`
	RunID         string        `json:"run_id"`
	ChildIndex    int64         `json:"child_index"`
	ArtifactPaths string        `json:"artifact_paths"`
	Error         string        `json:"error"`
	CreatedAt     int64         `json:"created_at"`
	UpdatedAt     int64         `json:"updated_at"`
	StartedAt     sql.NullInt64 `json:"started_at"`
	CompletedAt   sql.NullInt64 `json:"completed_at"`
}

func (q *Queries) InsertRunPipelinePhase(ctx context.Context, arg InsertRunPipelinePhaseParams) (RunPipelinePhase, error) {
	row := q.db.QueryRowContext(ctx, insertRunPipelinePhase,
		arg.PipelineID,
		arg.PhaseName,
		arg.PhaseOrder,
		arg.Enabled,
		arg.State,
		arg.RunID,
		arg.ChildIndex,
		arg.ArtifactPaths,
		arg.Error,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i RunPipelinePhase
	err := row.Scan(
		&i.PipelineID,
		&i.PhaseName,
		&i.PhaseOrder,
		&i.Enabled,
		&i.State,
		&i.RunID,
		&i.ChildIndex,
		&i.ArtifactPaths,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const isTaskCompleted = `-- name: IsTaskCompleted :one
SELECT status = 'completed'
FROM tasks
WHERE id = ?
`

func (q *Queries) IsTaskCompleted(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isTaskCompleted, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const lastRunForTask = `-- name: LastRunForTask :one
SELECT seq, id, task_id, repo, task, agent_backend, base_branch, head_branch, trigger, debug, status, run_dir, issue_number, pr_number, pr_url, pr_status, head_sha, context, error, created_at, updated_at, started_at, completed_at
FROM runs
WHERE task_id = ?
ORDER BY seq DESC
LIMIT 1
`

type LastRunForTaskRow struct {
	Seq          int64         `json:"seq"`
	ID           string        `json:"id"`
	TaskID       string        `json:"task_id"`
	Repo         string        `json:"repo"`
	Task         string        `json:"task"`
	AgentBackend string        `json:"agent_backend"`
	BaseBranch   string        `json:"base_branch"`
	HeadBranch   string        `json:"head_branch"`
	Trigger      string        `json:"trigger"`
	Debug        bool          `json:"debug"`
	Status       string        `json:"status"`
	RunDir       string        `json:"run_dir"`
	IssueNumber  int64         `json:"issue_number"`
	PrNumber     int64         `json:"pr_number"`
	PrUrl        string        `json:"pr_url"`
	PrStatus     string        `json:"pr_status"`
	HeadSha      string        `json:"head_sha"`
	Context      string        `json:"context"`
	Error        string        `json:"error"`
	CreatedAt    int64         `json:"created_at"`
	UpdatedAt    int64         `json:"updated_at"`
	StartedAt    sql.NullInt64 `json:"started_at"`
	CompletedAt  sql.NullInt64 `json:"completed_at"`
}

func (q *Queries) LastRunForTask(ctx context.Context, taskID string) (LastRunForTaskRow, error) {
	row := q.db.QueryRowContext(ctx, lastRunForTask, taskID)
	var i LastRunForTaskRow
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.TaskID,
		&i.Repo,
		&i.Task,
		&i.AgentBackend,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Trigger,
		&i.Debug,
		&i.Status,
		&i.RunDir,
		&i.IssueNumber,
		&i.PrNumber,
		&i.PrUrl,
		&i.PrStatus,
		&i.HeadSha,
		&i.Context,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listAllCodexCredentials = `-- name: ListAllCodexCredentials :many
SELECT
  id,
  owner_user_id,
  scope,
  encrypted_auth_blob,
  weight,
  status,
  cooldown_until,
  last_error,
  created_at,
  updated_at
FROM codex_credentials
ORDER BY created_at DESC
`

func (q *Queries) ListAllCodexCredentials(ctx context.Context) ([]CodexCredential, error) {
	rows, err := q.db.QueryContext(ctx, listAllCodexCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CodexCredential{}
	for rows.Next() {
		var i CodexCredential
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Scope,
			&i.EncryptedAuthBlob,
			&i.Weight,
			&i.Status,
			&i.CooldownUntil,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCodexCredentialsByOwner = `-- name: ListCodexCredentialsByOwner :many
SELECT
  id,
  owner_user_id,
  scope,
  encrypted_auth_blob,
  weight,
  status,
  cooldown_until,
  last_error,
  created_at,
  updated_at
FROM codex_credentials
WHERE owner_user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListCodexCredentialsByOwner(ctx context.Context, ownerUserID sql.NullString) ([]CodexCredential, error) {
	rows, err := q.db.QueryContext(ctx, listCodexCredentialsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CodexCredential{}
	for rows.Next() {
		var i CodexCredential
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Scope,
			&i.EncryptedAuthBlob,
			&i.Weight,
			&i.Status,
			&i.CooldownUntil,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialCandidates = `-- name: ListCredentialCandidates :many
SELECT
  c.id,
  c.owner_user_id,
  c.scope,
  c.weight,
  c.status,
  c.cooldown_until,
  CAST(COALESCE((
    SELECT COUNT(*)
    FROM credential_leases AS l
    WHERE l.credential_id = c.id
      AND l.released_at IS NULL
      AND l.expires_at > ?1
  ), 0) AS INTEGER) AS active_leases,
  CAST(COALESCE((
    SELECT SUM(u.tokens)
    FROM credential_usage AS u
    WHERE u.credential_id = c.id
      AND u.window_start >= ?2
  ), 0) AS INTEGER) AS usage_tokens,
  CAST(COALESCE((
    SELECT SUM(u.runs)
    FROM credential_usage AS u
    WHERE u.credential_id = c.id
      AND u.window_start >= ?2
  ), 0) AS INTEGER) AS usage_runs,
  c.last_error,
  c.created_at,
  c.updated_at
FROM codex_credentials AS c
WHERE c.status = 'active'
  AND (c.cooldown_until IS NULL OR c.cooldown_until <= ?1)
  AND (c.scope = 'shared' OR c.owner_user_id = ?3)
ORDER BY c.created_at ASC, c.id ASC
`

type ListCredentialCandidatesParams struct {
	Now              int64          `json:"now"`
	UsageWindowStart int64          `json:"usage_window_start"`
	RequesterUserID  sql.NullString `json:"requester_user_id"`
}

type ListCredentialCandidatesRow struct {
	ID            string         `json:"id"`
	OwnerUserID   sql.NullString `json:"owner_user_id"`
	Scope         string         `json:"scope"`
	Weight        int64          `json:"weight"`
	Status        string         `json:"status"`
	CooldownUntil sql.NullInt64  `json:"cooldown_until"`
	ActiveLeases  int64          `json:"active_leases"`
	UsageTokens   int64          `json:"usage_tokens"`
	UsageRuns     int64          `json:"usage_runs"`
	LastError     string         `json:"last_error"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
}

func (q *Queries) ListCredentialCandidates(ctx context.Context, arg ListCredentialCandidatesParams) ([]ListCredentialCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCredentialCandidates, arg.Now, arg.UsageWindowStart, arg.RequesterUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCredentialCandidatesRow{}
	for rows.Next() {
		var i ListCredentialCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Scope,
			&i.Weight,
			&i.Status,
			&i.CooldownUntil,
			&i.ActiveLeases,
			&i.UsageTokens,
			&i.UsageRuns,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncompleteRunPipelines = `-- name: ListIncompleteRunPipelines :many
SELECT
  id,
  task_id,
  repo,
  task,
  base_branch,
  head_branch,
  trigger,
  issue_number,
  pr_number,
  context,
  debug,
  created_by_user_id,
  artifact_dir,
  status,
  active_phase,
  failed_phase,
  cancel_requested,
  max_phases,
  max_child_runs_per_phase,
  total_child_runs,
  token_budget_total,
  token_budget_used,
  deadline_at,
  created_at,
  updated_at,
  completed_at
FROM run_pipelines
WHERE status IN ('pending', 'running')
ORDER BY created_at ASC
`

func (q *Queries) ListIncompleteRunPipelines(ctx context.Context) ([]RunPipeline, error) {
	rows, err := q.db.QueryContext(ctx, listIncompleteRunPipelines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunPipeline{}
	for rows.Next() {
		var i RunPipeline
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Repo,
			&i.Task,
			&i.BaseBranch,
			&i.HeadBranch,
			&i.Trigger,
			&i.IssueNumber,
			&i.PrNumber,
			&i.Context,
			&i.Debug,
			&i.CreatedByUserID,
			&i.ArtifactDir,
			&i.Status,
			&i.ActivePhase,
			&i.FailedPhase,
			&i.CancelRequested,
			&i.MaxPhases,
			&i.MaxChildRunsPerPhase,
			&i.TotalChildRuns,
			&i.TokenBudgetTotal,
			&i.TokenBudgetUsed,
			&i.DeadlineAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunPipelinePhases = `-- name: ListRunPipelinePhases :many
SELECT
  pipeline_id,
  phase_name,
  phase_order,
  enabled,
  state,
  run_id,
  child_index,
  artifact_paths,
  error,
  created_at,
  updated_at,
  started_at,
  completed_at
FROM run_pipeline_phases
WHERE pipeline_id = ?
ORDER BY phase_order ASC
`

func (q *Queries) ListRunPipelinePhases(ctx context.Context, pipelineID string) ([]RunPipelinePhase, error) {
	rows, err := q.db.QueryContext(ctx, listRunPipelinePhases, pipelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunPipelinePhase{}
	for rows.Next() {
		var i RunPipelinePhase
		if err := rows.Scan(
			&i.PipelineID,
			&i.PhaseName,
			&i.PhaseOrder,
			&i.Enabled,
			&i.State,
			&i.RunID,
			&i.ChildIndex,
			&i.ArtifactPaths,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningRuns = `-- name: ListRunningRuns :many
SELECT seq, id, task_id, repo, task, agent_backend, base_branch, head_branch, trigger, debug, status, run_dir, issue_number, pr_number, pr_url, pr_status, head_sha, context, error, created_at, updated_at, started_at, completed_at
FROM runs
WHERE status = 'running'
ORDER BY seq DESC
`

type ListRunningRunsRow struct {
	Seq          int64         `json:"seq"`
	ID           string        `json:"id"`
	TaskID       string        `json:"task_id"`
	Repo         string        `json:"repo"`
	Task         string        `json:"task"`
	AgentBackend string        `json:"agent_backend"`
	BaseBranch   string        `json:"base_branch"`
	HeadBranch   string        `json:"head_branch"`
	Trigger      string        `json:"trigger"`
	Debug        bool          `json:"debug"`
	Status       string        `json:"status"`
	RunDir       string        `json:"run_dir"`
	IssueNumber  int64         `json:"issue_number"`
	PrNumber     int64         `json:"pr_number"`
	PrUrl        string        `json:"pr_url"`
	PrStatus     string        `json:"pr_status"`
	HeadSha      string        `json:"head_sha"`
	Context      string        `json:"context"`
	Error        string        `json:"error"`
	CreatedAt    int64         `json:"created_at"`
	UpdatedAt    int64         `json:"updated_at"`
	StartedAt    sql.NullInt64 `json:"started_at"`
	CompletedAt  sql.NullInt64 `json:"completed_at"`
}

func (q *Queries) ListRunningRuns(ctx context.Context) ([]ListRunningRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunningRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunningRunsRow{}
	for rows.Next() {
		var i ListRunningRunsRow
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.TaskID,
			&i.Repo,
			&i.Task,
			&i.AgentBackend,
			&i.BaseBranch,
			&i.HeadBranch,
			&i.Trigger,
			&i.Debug,
			&i.Status,
			&i.RunDir,
			&i.IssueNumber,
			&i.PrNumber,
			&i.PrUrl,
			&i.PrStatus,
			&i.HeadSha,
			&i.Context,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT seq, id, task_id, repo, task, agent_backend, base_branch, head_branch, trigger, debug, status, run_dir, issue_number, pr_number, pr_url, pr_status, head_sha, context, error, created_at, updated_at, started_at, completed_at
FROM runs
ORDER BY seq DESC
LIMIT ?
`

type ListRunsRow struct {
	Seq          int64         `json:"seq"`
	ID           string        `json:"id"`
	TaskID       string        `json:"task_id"`
	Repo         string        `json:"repo"`
	Task         string        `json:"task"`
	AgentBackend string        `json:"agent_backend"`
	BaseBranch   string        `json:"base_branch"`
	HeadBranch   string        `json:"head_branch"`
	Trigger      string        `json:"trigger"`
	Debug        bool          `json:"debug"`
	Status       string        `json:"status"`
	RunDir       string        `json:"run_dir"`
	IssueNumber  int64         `json:"issue_number"`
	PrNumber     int64         `json:"pr_number"`
	PrUrl        string        `json:"pr_url"`
	PrStatus     string        `json:"pr_status"`
	HeadSha      string        `json:"head_sha"`
	Context      string        `json:"context"`
	Error        string        `json:"error"`
	CreatedAt    int64         `json:"created_at"`
	UpdatedAt    int64         `json:"updated_at"`
	StartedAt    sql.NullInt64 `json:"started_at"`
	CompletedAt  sql.NullInt64 `json:"completed_at"`
}

func (q *Queries) ListRuns(ctx context.Context, limit int64) ([]ListRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsRow{}
	for rows.Next() {
		var i ListRunsRow
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.TaskID,
			&i.Repo,
			&i.Task,
			&i.AgentBackend,
			&i.BaseBranch,
			&i.HeadBranch,
			&i.Trigger,
			&i.Debug,
			&i.Status,
			&i.RunDir,
			&i.IssueNumber,
			&i.PrNumber,
			&i.PrUrl,
			&i.PrStatus,
			&i.HeadSha,
			&i.Context,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedCodexCredentials = `-- name: ListSharedCodexCredentials :many
SELECT
  id,
  owner_user_id,
  scope,
  encrypted_auth_blob,
  weight,
  status,
  cooldown_until,
  last_error,
  created_at,
  updated_at
FROM codex_credentials
WHERE scope = 'shared'
ORDER BY created_at DESC
`

func (q *Queries) ListSharedCodexCredentials(ctx context.Context) ([]CodexCredential, error) {
	rows, err := q.db.QueryContext(ctx, listSharedCodexCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CodexCredential{}
	for rows.Next() {
		var i CodexCredential
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Scope,
			&i.EncryptedAuthBlob,
			&i.Weight,
			&i.Status,
			&i.CooldownUntil,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskCompleted = `-- name: MarkTaskCompleted :execrows
UPDATE tasks
SET status = 'completed', updated_at = ?
WHERE id = ?
`

type MarkTaskCompletedParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) MarkTaskCompleted(ctx context.Context, arg MarkTaskCompletedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markTaskCompleted, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markTaskOpen = `-- name: MarkTaskOpen :execrows
UPDATE tasks
SET status = 'open', updated_at = ?
WHERE id = ?
`

type MarkTaskOpenParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) MarkTaskOpen(ctx context.Context, arg MarkTaskOpenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markTaskOpen, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reclaimExpiredCredentialLeases = `-- name: ReclaimExpiredCredentialLeases :execrows
UPDATE credential_leases
SET released_at = ?
WHERE released_at IS NULL
  AND expires_at <= ?
`

type ReclaimExpiredCredentialLeasesParams struct {
	ReleasedAt sql.NullInt64 `json:"released_at"`
	ExpiresAt  int64         `json:"expires_at"`
}

func (q *Queries) ReclaimExpiredCredentialLeases(ctx context.Context, arg ReclaimExpiredCredentialLeasesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reclaimExpiredCredentialLeases, arg.ReleasedAt, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordDelivery = `-- name: RecordDelivery :exec
INSERT OR REPLACE INTO deliveries (
  id,
  status,
  claim_token,
  claimed_by,
  claimed_at,
  processed_at,
  seen_at,
  last_error
)
VALUES (?, 'processed', '', '', 0, ?, ?, '')
`

type RecordDeliveryParams struct {
	ID          string        `json:"id"`
	ProcessedAt sql.NullInt64 `json:"processed_at"`
	SeenAt      int64         `json:"seen_at"`
}

func (q *Queries) RecordDelivery(ctx context.Context, arg RecordDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, recordDelivery, arg.ID, arg.ProcessedAt, arg.SeenAt)
	return err
}

const releaseCredentialLease = `-- name: ReleaseCredentialLease :one
UPDATE credential_leases
SET released_at = ?
WHERE id = ?
  AND released_at IS NULL
RETURNING id, credential_id, run_id, user_id, strategy, acquired_at, expires_at, released_at
`

type ReleaseCredentialLeaseParams struct {
	ReleasedAt sql.NullInt64 `json:"released_at"`
	ID         string        `json:"id"`
}

func (q *Queries) ReleaseCredentialLease(ctx context.Context, arg ReleaseCredentialLeaseParams) (CredentialLease, error) {
	row := q.db.QueryRowContext(ctx, releaseCredentialLease, arg.ReleasedAt, arg.ID)
	var i CredentialLease
	err := row.Scan(
		&i.ID,
		&i.CredentialID,
		&i.RunID,
		&i.UserID,
		&i.Strategy,
		&i.AcquiredAt,
		&i.ExpiresAt,
		&i.ReleasedAt,
	)
	return i, err
}

const releaseCredentialLeaseByRunID = `-- name: ReleaseCredentialLeaseByRunID :execrows
UPDATE credential_leases
SET released_at = ?
WHERE run_id = ?
  AND released_at IS NULL
`

type ReleaseCredentialLeaseByRunIDParams struct {
	ReleasedAt sql.NullInt64 `json:"released_at"`
	RunID      string        `json:"run_id"`
}

func (q *Queries) ReleaseCredentialLeaseByRunID(ctx context.Context, arg ReleaseCredentialLeaseByRunIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseCredentialLeaseByRunID, arg.ReleasedAt, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const releaseDeliveryClaim = `-- name: ReleaseDeliveryClaim :execrows
DELETE FROM deliveries
WHERE id = ? AND claim_token = ?
`

type ReleaseDeliveryClaimParams struct {
	ID         string `json:"id"`
	ClaimToken string `json:"claim_token"`
}

func (q *Queries) ReleaseDeliveryClaim(ctx context.Context, arg ReleaseDeliveryClaimParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseDeliveryClaim, arg.ID, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const renewCredentialLease = `-- name: RenewCredentialLease :execrows
UPDATE credential_leases
SET expires_at = ?
WHERE id = ?
  AND released_at IS NULL
  AND expires_at > ?
`

type RenewCredentialLeaseParams struct {
	ExpiresAt   int64  `json:"expires_at"`
	ID          string `json:"id"`
	ExpiresAt_2 int64  `json:"expires_at_2"`
}

func (q *Queries) RenewCredentialLease(ctx context.Context, arg RenewCredentialLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewCredentialLease, arg.ExpiresAt, arg.ID, arg.ExpiresAt_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const renewRunLease = `-- name: RenewRunLease :execrows
UPDATE run_leases
SET
  heartbeat_at = ?,
  lease_expires_at = ?
WHERE run_id = ? AND owner_id = ?
`

type RenewRunLeaseParams struct {
	HeartbeatAt    int64  `json:"heartbeat_at"`
	LeaseExpiresAt int64  `json:"lease_expires_at"`
	RunID          string `json:"run_id"`
	OwnerID        string `json:"owner_id"`
}

func (q *Queries) RenewRunLease(ctx context.Context, arg RenewRunLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewRunLease,
		arg.HeartbeatAt,
		arg.LeaseExpiresAt,
		arg.RunID,
		arg.OwnerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setCodexCredentialStatus = `-- name: SetCodexCredentialStatus :execrows
UPDATE codex_credentials
SET
  status = ?,
  cooldown_until = ?,
  last_error = ?,
  updated_at = ?
WHERE id = ?
`

type SetCodexCredentialStatusParams struct {
	Status        string        `json:"status"`
	CooldownUntil sql.NullInt64 `json:"cooldown_until"`
	LastError     string        `json:"last_error"`
	UpdatedAt     int64         `json:"updated_at"`
	ID            string        `json:"id"`
}

func (q *Queries) SetCodexCredentialStatus(ctx context.Context, arg SetCodexCredentialStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setCodexCredentialStatus,
		arg.Status,
		arg.CooldownUntil,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setRunCreatedByUser = `-- name: SetRunCreatedByUser :execrows
UPDATE runs
SET created_by_user_id = ?, updated_at = ?
WHERE id = ?
`

type SetRunCreatedByUserParams struct {
	CreatedByUserID string `json:"created_by_user_id"`
	UpdatedAt       int64  `json:"updated_at"`
	ID              string `json:"id"`
}

func (q *Queries) SetRunCreatedByUser(ctx context.Context, arg SetRunCreatedByUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setRunCreatedByUser, arg.CreatedByUserID, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setRunCredentialID = `-- name: SetRunCredentialID :execrows
UPDATE runs
SET credential_id = ?, updated_at = ?
WHERE id = ?
`

type SetRunCredentialIDParams struct {
	CredentialID string `json:"credential_id"`
	UpdatedAt    int64  `json:"updated_at"`
	ID           string `json:"id"`
}

func (q *Queries) SetRunCredentialID(ctx context.Context, arg SetRunCredentialIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setRunCredentialID, arg.CredentialID, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTaskCreatedByUser = `-- name: SetTaskCreatedByUser :execrows
UPDATE tasks
SET created_by_user_id = ?, updated_at = ?
WHERE id = ?
`

type SetTaskCreatedByUserParams struct {
	CreatedByUserID string `json:"created_by_user_id"`
	UpdatedAt       int64  `json:"updated_at"`
	ID              string `json:"id"`
}

func (q *Queries) SetTaskCreatedByUser(ctx context.Context, arg SetTaskCreatedByUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTaskCreatedByUser, arg.CreatedByUserID, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTaskLastRun = `-- name: SetTaskLastRun :execrows
UPDATE tasks
SET
  last_run_id = ?1,
  updated_at = ?2,
  issue_number = COALESCE(?3, issue_number),
  pr_number = COALESCE(?4, pr_number)
WHERE id = ?5
`

type SetTaskLastRunParams struct {
	LastRunID   string        `json:"last_run_id"`
	UpdatedAt   int64         `json:"updated_at"`
	IssueNumber sql.NullInt64 `json:"issue_number"`
	PrNumber    sql.NullInt64 `json:"pr_number"`
	ID          string        `json:"id"`
}

func (q *Queries) SetTaskLastRun(ctx context.Context, arg SetTaskLastRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTaskLastRun,
		arg.LastRunID,
		arg.UpdatedAt,
		arg.IssueNumber,
		arg.PrNumber,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTaskPR = `-- name: SetTaskPR :execrows
UPDATE tasks
SET pr_number = ?, updated_at = ?
WHERE id = ?
`

type SetTaskPRParams struct {
	PrNumber  int64  `json:"pr_number"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) SetTaskPR(ctx context.Context, arg SetTaskPRParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTaskPR, arg.PrNumber, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :execrows
UPDATE api_keys
SET last_used_at = ?
WHERE id = ?
`

type TouchAPIKeyLastUsedParams struct {
	LastUsedAt int64  `json:"last_used_at"`
	ID         string `json:"id"`
}

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, arg TouchAPIKeyLastUsedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchAPIKeyLastUsed, arg.LastUsedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const trimOldRuns = `-- name: TrimOldRuns :exec
DELETE FROM runs
WHERE id IN (
  SELECT id
  FROM runs
  ORDER BY seq DESC
  LIMIT -1 OFFSET ?
)
`

func (q *Queries) TrimOldRuns(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, trimOldRuns, offset)
	return err
}

const tryCreateCredentialLease = `-- name: TryCreateCredentialLease :execrows
INSERT INTO credential_leases (
  id,
  credential_id,
  run_id,
  user_id,
  strategy,
  acquired_at,
  expires_at,
  released_at
)
SELECT
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  NULL
WHERE EXISTS (
  SELECT 1
  FROM codex_credentials AS c
  WHERE c.id = ?2
    AND c.status = 'active'
    AND (c.cooldown_until IS NULL OR c.cooldown_until <= ?8)
    AND (
      c.scope = 'shared'
      OR (c.scope = 'personal' AND c.owner_user_id = ?4)
    )
)
AND NOT EXISTS (
  SELECT 1
  FROM credential_leases AS existing
  WHERE existing.run_id = ?3
    AND existing.released_at IS NULL
    AND existing.expires_at > ?8
)
`

type TryCreateCredentialLeaseParams struct {
	ID           string        `json:"id"`
	CredentialID string        `json:"credential_id"`
	RunID        string        `json:"run_id"`
	UserID       string        `json:"user_id"`
	Strategy     string        `json:"strategy"`
	AcquiredAt   int64         `json:"acquired_at"`
	ExpiresAt    int64         `json:"expires_at"`
	Now          sql.NullInt64 `json:"now"`
}

func (q *Queries) TryCreateCredentialLease(ctx context.Context, arg TryCreateCredentialLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, tryCreateCredentialLease,
		arg.ID,
		arg.CredentialID,
		arg.RunID,
		arg.UserID,
		arg.Strategy,
		arg.AcquiredAt,
		arg.ExpiresAt,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCodexCredential = `-- name: UpdateCodexCredential :execrows
UPDATE codex_credentials
SET
  owner_user_id = ?,
  scope = ?,
  encrypted_auth_blob = ?,
  weight = ?,
  status = ?,
  cooldown_until = ?,
  last_error = ?,
  updated_at = ?
WHERE id = ?
`

type UpdateCodexCredentialParams struct {
	OwnerUserID       sql.NullString `json:"owner_user_id"`
	Scope             string         `json:"scope"`
	EncryptedAuthBlob []byte         `json:"encrypted_auth_blob"`
	Weight            int64          `json:"weight"`
	Status            string         `json:"status"`
	CooldownUntil     sql.NullInt64  `json:"cooldown_until"`
	LastError         string         `json:"last_error"`
	UpdatedAt         int64          `json:"updated_at"`
	ID                string         `json:"id"`
}

func (q *Queries) UpdateCodexCredential(ctx context.Context, arg UpdateCodexCredentialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCodexCredential,
		arg.OwnerUserID,
		arg.Scope,
		arg.EncryptedAuthBlob,
		arg.Weight,
		arg.Status,
		arg.CooldownUntil,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRun = `-- name: UpdateRun :execrows
UPDATE runs
SET
  task_id = ?,
  repo = ?,
  task = ?,
  agent_backend = ?,
  base_branch = ?,
  head_branch = ?,
  trigger = ?,
  debug = ?,
  status = ?,
  run_dir = ?,
  issue_number = ?,
  pr_number = ?,
  pr_url = ?,
  pr_status = ?,
  head_sha = ?,
  context = ?,
  error = ?,
  created_at = ?,
  updated_at = ?,
  started_at = ?,
  completed_at = ?
WHERE id = ?
`

type UpdateRunParams struct {
	TaskID       string        `json:"task_id"`
	Repo         string        `json:"repo"`
	Task         string        `json:"task"`
	AgentBackend string        `json:"agent_backend"`
	BaseBranch   string        `json:"base_branch"`
	HeadBranch   string        `json:"head_branch"`
	Trigger      string        `json:"trigger"`
	Debug        bool          `json:"debug"`
	Status       string        `json:"status"`
	RunDir       string        `json:"run_dir"`
	IssueNumber  int64         `json:"issue_number"`
	PrNumber     int64         `json:"pr_number"`
	PrUrl        string        `json:"pr_url"`
	PrStatus     string        `json:"pr_status"`
	HeadSha      string        `json:"head_sha"`
	Context      string        `json:"context"`
	Error        string        `json:"error"`
	CreatedAt    int64         `json:"created_at"`
	UpdatedAt    int64         `json:"updated_at"`
	StartedAt    sql.NullInt64 `json:"started_at"`
	CompletedAt  sql.NullInt64 `json:"completed_at"`
	ID           string        `json:"id"`
}

func (q *Queries) UpdateRun(ctx context.Context, arg UpdateRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRun,
		arg.TaskID,
		arg.Repo,
		arg.Task,
		arg.AgentBackend,
		arg.BaseBranch,
		arg.HeadBranch,
		arg.Trigger,
		arg.Debug,
		arg.Status,
		arg.RunDir,
		arg.IssueNumber,
		arg.PrNumber,
		arg.PrUrl,
		arg.PrStatus,
		arg.HeadSha,
		arg.Context,
		arg.Error,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRunExecutionState = `-- name: UpdateRunExecutionState :execrows
UPDATE run_executions
SET
  status = ?,
  exit_code = ?,
  updated_at = ?,
  last_observed_at = ?
WHERE run_id = ?
`

type UpdateRunExecutionStateParams struct {
	Status         string `json:"status"`
	ExitCode       int64  `json:"exit_code"`
	UpdatedAt      int64  `json:"updated_at"`
	LastObservedAt int64  `json:"last_observed_at"`
	RunID          string `json:"run_id"`
}

func (q *Queries) UpdateRunExecutionState(ctx context.Context, arg UpdateRunExecutionStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRunExecutionState,
		arg.Status,
		arg.ExitCode,
		arg.UpdatedAt,
		arg.LastObservedAt,
		arg.RunID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRunPipeline = `-- name: UpdateRunPipeline :execrows
UPDATE run_pipelines
SET
  task_id = ?,
  repo = ?,
  task = ?,
  base_branch = ?,
  head_branch = ?,
  trigger = ?,
  issue_number = ?,
  pr_number = ?,
  context = ?,
  debug = ?,
  created_by_user_id = ?,
  artifact_dir = ?,
  status = ?,
  active_phase = ?,
  failed_phase = ?,
  cancel_requested = ?,
  max_phases = ?,
  max_child_runs_per_phase = ?,
  total_child_runs = ?,
  token_budget_total = ?,
  token_budget_used = ?,
  deadline_at = ?,
  created_at = ?,
  updated_at = ?,
  completed_at = ?
WHERE id = ?
`

type UpdateRunPipelineParams struct {
	TaskID               string        `json:"task_id"`
	Repo                 string        `json:"repo"`
	Task                 string        `json:"task"`
	BaseBranch           string        `json:"base_branch"`
	HeadBranch           string        `json:"head_branch"`
	Trigger              string        `json:"trigger"`
	IssueNumber          int64         `json:"issue_number"`
	PrNumber             int64         `json:"pr_number"`
	Context              string        `json:"context"`
	Debug                bool          `json:"debug"`
	CreatedByUserID      string        `json:"created_by_user_id"`
	ArtifactDir          string        `json:"artifact_dir"`
	Status               string        `json:"status"`
	ActivePhase          string        `json:"active_phase"`
	FailedPhase          string        `json:"failed_phase"`
	CancelRequested      bool          `json:"cancel_requested"`
	MaxPhases            int64         `json:"max_phases"`
	MaxChildRunsPerPhase int64         `json:"max_child_runs_per_phase"`
	TotalChildRuns       int64         `json:"total_child_runs"`
	TokenBudgetTotal     int64         `json:"token_budget_total"`
	TokenBudgetUsed      int64         `json:"token_budget_used"`
	DeadlineAt           sql.NullInt64 `json:"deadline_at"`
	CreatedAt            int64         `json:"created_at"`
	UpdatedAt            int64         `json:"updated_at"`
	CompletedAt          sql.NullInt64 `json:"completed_at"`
	ID                   string        `json:"id"`
}

func (q *Queries) UpdateRunPipeline(ctx context.Context, arg UpdateRunPipelineParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRunPipeline,
		arg.TaskID,
		arg.Repo,
		arg.Task,
		arg.BaseBranch,
		arg.HeadBranch,
		arg.Trigger,
		arg.IssueNumber,
		arg.PrNumber,
		arg.Context,
		arg.Debug,
		arg.CreatedByUserID,
		arg.ArtifactDir,
		arg.Status,
		arg.ActivePhase,
		arg.FailedPhase,
		arg.CancelRequested,
		arg.MaxPhases,
		arg.MaxChildRunsPerPhase,
		arg.TotalChildRuns,
		arg.TokenBudgetTotal,
		arg.TokenBudgetUsed,
		arg.DeadlineAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CompletedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRunPipelinePhase = `-- name: UpdateRunPipelinePhase :execrows
UPDATE run_pipeline_phases
SET
  phase_order = ?,
  enabled = ?,
  state = ?,
  run_id = ?,
  child_index = ?,
  artifact_paths = ?,
  error = ?,
  created_at = ?,
  updated_at = ?,
  started_at = ?,
  completed_at = ?
WHERE pipeline_id = ? AND phase_name = ?
`

type UpdateRunPipelinePhaseParams struct {
	PhaseOrder    int64         `json:"phase_order"`
	Enabled       bool          `json:"enabled"`
	State         string        `json:"state"`
	RunID         string        `json:"run_id"`
	ChildIndex    int64         `json:"child_index"`
	ArtifactPaths string        `json:"artifact_paths"`
	Error         string        `json:"error"`
	CreatedAt     int64         `json:"created_at"`
	UpdatedAt     int64         `json:"updated_at"`
	StartedAt     sql.NullInt64 `json:"started_at"`
	CompletedAt   sql.NullInt64 `json:"completed_at"`
	PipelineID    string        `json:"pipeline_id"`
	PhaseName     string        `json:"phase_name"`
}

func (q *Queries) UpdateRunPipelinePhase(ctx context.Context, arg UpdateRunPipelinePhaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRunPipelinePhase,
		arg.PhaseOrder,
		arg.Enabled,
		arg.State,
		arg.RunID,
		arg.ChildIndex,
		arg.ArtifactPaths,
		arg.Error,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.PipelineID,
		arg.PhaseName,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertAPIKey = `-- name: UpsertAPIKey :exec
INSERT INTO api_keys (
  id,
  user_id,
  key_hash,
  label,
  created_at,
  last_used_at,
  disabled_at
)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(key_hash) DO UPDATE SET
  user_id = excluded.user_id,
  label = excluded.label,
  disabled_at = excluded.disabled_at
`

type UpsertAPIKeyParams struct {
	ID         string        `json:"id"`
	UserID     string        `json:"user_id"`
	KeyHash    string        `json:"key_hash"`
	Label      string        `json:"label"`
	CreatedAt  int64         `json:"created_at"`
	LastUsedAt int64         `json:"last_used_at"`
	DisabledAt sql.NullInt64 `json:"disabled_at"`
}

func (q *Queries) UpsertAPIKey(ctx context.Context, arg UpsertAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, upsertAPIKey,
		arg.ID,
		arg.UserID,
		arg.KeyHash,
		arg.Label,
		arg.CreatedAt,
		arg.LastUsedAt,
		arg.DisabledAt,
	)
	return err
}

const upsertCredentialUsage = `-- name: UpsertCredentialUsage :exec
INSERT INTO credential_usage (
  credential_id,
  window_start,
  tokens,
  runs
)
VALUES (?, ?, ?, ?)
ON CONFLICT(credential_id, window_start) DO UPDATE SET
  tokens = credential_usage.tokens + excluded.tokens,
  runs = credential_usage.runs + excluded.runs
`

type UpsertCredentialUsageParams struct {
	CredentialID string `json:"credential_id"`
	WindowStart  int64  `json:"window_start"`
	Tokens       int64  `json:"tokens"`
	Runs         int64  `json:"runs"`
}

func (q *Queries) UpsertCredentialUsage(ctx context.Context, arg UpsertCredentialUsageParams) error {
	_, err := q.db.ExecContext(ctx, upsertCredentialUsage,
		arg.CredentialID,
		arg.WindowStart,
		arg.Tokens,
		arg.Runs,
	)
	return err
}

const upsertRunCancel = `-- name: UpsertRunCancel :exec
INSERT INTO run_cancels (run_id, reason, source, requested_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(run_id) DO UPDATE SET
  reason = excluded.reason,
  source = excluded.source,
  requested_at = excluded.requested_at
`

type UpsertRunCancelParams struct {
	RunID       string `json:"run_id"`
	Reason      string `json:"reason"`
	Source      string `json:"source"`
	RequestedAt int64  `json:"requested_at"`
}

func (q *Queries) UpsertRunCancel(ctx context.Context, arg UpsertRunCancelParams) error {
	_, err := q.db.ExecContext(ctx, upsertRunCancel,
		arg.RunID,
		arg.Reason,
		arg.Source,
		arg.RequestedAt,
	)
	return err
}

const upsertRunExecution = `-- name: UpsertRunExecution :exec
INSERT INTO run_executions (
  run_id,
  backend,
  container_name,
  container_id,
  status,
  exit_code,
  created_at,
  updated_at,
  last_observed_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(run_id) DO UPDATE SET
  backend = excluded.backend,
  container_name = excluded.container_name,
  container_id = excluded.container_id,
  status = excluded.status,
  exit_code = excluded.exit_code,
  updated_at = excluded.updated_at,
  last_observed_at = excluded.last_observed_at
`

type UpsertRunExecutionParams struct {
	RunID          string `json:"run_id"`
	Backend        string `json:"backend"`
	ContainerName  string `json:"container_name"`
	ContainerID    string `json:"container_id"`
	Status         string `json:"status"`
	ExitCode       int64  `json:"exit_code"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
	LastObservedAt int64  `json:"last_observed_at"`
}

func (q *Queries) UpsertRunExecution(ctx context.Context, arg UpsertRunExecutionParams) error {
	_, err := q.db.ExecContext(ctx, upsertRunExecution,
		arg.RunID,
		arg.Backend,
		arg.ContainerName,
		arg.ContainerID,
		arg.Status,
		arg.ExitCode,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastObservedAt,
	)
	return err
}

const upsertRunLease = `-- name: UpsertRunLease :exec
INSERT INTO run_leases (run_id, owner_id, heartbeat_at, lease_expires_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(run_id) DO UPDATE SET
  owner_id = excluded.owner_id,
  heartbeat_at = excluded.heartbeat_at,
  lease_expires_at = excluded.lease_expires_at
`

type UpsertRunLeaseParams struct {
	RunID          string `json:"run_id"`
	OwnerID        string `json:"owner_id"`
	HeartbeatAt    int64  `json:"heartbeat_at"`
	LeaseExpiresAt int64  `json:"lease_expires_at"`
}

func (q *Queries) UpsertRunLease(ctx context.Context, arg UpsertRunLeaseParams) error {
	_, err := q.db.ExecContext(ctx, upsertRunLease,
		arg.RunID,
		arg.OwnerID,
		arg.HeartbeatAt,
		arg.LeaseExpiresAt,
	)
	return err
}

const upsertRunTokenUsage = `-- name: UpsertRunTokenUsage :one
INSERT INTO run_token_usage (
  run_id,
  backend,
  provider,
  model,
  total_tokens,
  input_tokens,
  output_tokens,
  cached_input_tokens,
  reasoning_output_tokens,
  raw_usage_json,
  captured_at,
  created_at,
  updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(run_id) DO UPDATE SET
  backend = excluded.backend,
  provider = excluded.provider,
  model = excluded.model,
  total_tokens = excluded.total_tokens,
  input_tokens = excluded.input_tokens,
  output_tokens = excluded.output_tokens,
  cached_input_tokens = excluded.cached_input_tokens,
  reasoning_output_tokens = excluded.reasoning_output_tokens,
  raw_usage_json = excluded.raw_usage_json,
  captured_at = excluded.captured_at,
  updated_at = excluded.updated_at
RETURNING
  run_id,
  backend,
  provider,
  model,
  total_tokens,
  input_tokens,
  output_tokens,
  cached_input_tokens,
  reasoning_output_tokens,
  raw_usage_json,
  captured_at,
  created_at,
  updated_at
`

type UpsertRunTokenUsageParams struct {
	RunID                 string        `json:"run_id"`
	Backend               string        `json:"backend"`
	Provider              string        `json:"provider"`
	Model                 string        `json:"model"`
	TotalTokens           int64         `json:"total_tokens"`
	InputTokens           sql.NullInt64 `json:"input_tokens"`
	OutputTokens          sql.NullInt64 `json:"output_tokens"`
	CachedInputTokens     sql.NullInt64 `json:"cached_input_tokens"`
	ReasoningOutputTokens sql.NullInt64 `json:"reasoning_output_tokens"`
	RawUsageJson          string        `json:"raw_usage_json"`
	CapturedAt            int64         `json:"captured_at"`
	CreatedAt             int64         `json:"created_at"`
	UpdatedAt             int64         `json:"updated_at"`
}

func (q *Queries) UpsertRunTokenUsage(ctx context.Context, arg UpsertRunTokenUsageParams) (RunTokenUsage, error) {
	row := q.db.QueryRowContext(ctx, upsertRunTokenUsage,
		arg.RunID,
		arg.Backend,
		arg.Provider,
		arg.Model,
		arg.TotalTokens,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedInputTokens,
		arg.ReasoningOutputTokens,
		arg.RawUsageJson,
		arg.CapturedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i RunTokenUsage
	err := row.Scan(
		&i.RunID,
		&i.Backend,
		&i.Provider,
		&i.Model,
		&i.TotalTokens,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedInputTokens,
		&i.ReasoningOutputTokens,
		&i.RawUsageJson,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSchedulerPause = `-- name: UpsertSchedulerPause :one
INSERT INTO scheduler_pauses (
  scope,
  reason,
  paused_until,
  created_at,
  updated_at
)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5
)
ON CONFLICT(scope) DO UPDATE SET
  paused_until = CASE
    WHEN scheduler_pauses.paused_until > excluded.paused_until THEN scheduler_pauses.paused_until
    ELSE excluded.paused_until
  END,
  reason = CASE
    WHEN scheduler_pauses.paused_until > excluded.paused_until THEN scheduler_pauses.reason
    ELSE excluded.reason
  END,
  updated_at = excluded.updated_at
RETURNING
  scope,
  reason,
  paused_until,
  created_at,
  updated_at
`

type UpsertSchedulerPauseParams struct {
	Scope       string `json:"scope"`
	Reason      string `json:"reason"`
	PausedUntil int64  `json:"paused_until"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

func (q *Queries) UpsertSchedulerPause(ctx context.Context, arg UpsertSchedulerPauseParams) (SchedulerPause, error) {
	row := q.db.QueryRowContext(ctx, upsertSchedulerPause,
		arg.Scope,
		arg.Reason,
		arg.PausedUntil,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SchedulerPause
	err := row.Scan(
		&i.Scope,
		&i.Reason,
		&i.PausedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTask = `-- name: UpsertTask :exec
INSERT INTO tasks (
  id,
  repo,
  agent_backend,
  issue_number,
  pr_number,
  status,
  last_run_id,
  created_at,
  updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  repo = excluded.repo,
  agent_backend = excluded.agent_backend,
  issue_number = CASE WHEN excluded.issue_number > 0 THEN excluded.issue_number ELSE tasks.issue_number END,
  pr_number = CASE WHEN excluded.pr_number > 0 THEN excluded.pr_number ELSE tasks.pr_number END,
  updated_at = excluded.updated_at
`

type UpsertTaskParams struct {
	ID           string `json:"id"`
	Repo         string `json:"repo"`
	AgentBackend string `json:"agent_backend"`
	IssueNumber  int64  `json:"issue_number"`
	PrNumber     int64  `json:"pr_number"`
	Status       string `json:"status"`
	LastRunID    string `json:"last_run_id"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) UpsertTask(ctx context.Context, arg UpsertTaskParams) error {
	_, err := q.db.ExecContext(ctx, upsertTask,
		arg.ID,
		arg.Repo,
		arg.AgentBackend,
		arg.IssueNumber,
		arg.PrNumber,
		arg.Status,
		arg.LastRunID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertTaskAgentSession = `-- name: UpsertTaskAgentSession :exec
INSERT INTO task_agent_sessions (
  task_id,
  agent_backend,
  backend_session_id,
  session_key,
  session_root,
  last_run_id,
  created_at,
  updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(task_id) DO UPDATE SET
  agent_backend = excluded.agent_backend,
  backend_session_id = excluded.backend_session_id,
  session_key = excluded.session_key,
  session_root = excluded.session_root,
  last_run_id = excluded.last_run_id,
  updated_at = excluded.updated_at
`

type UpsertTaskAgentSessionParams struct {
	TaskID           string `json:"task_id"`
	AgentBackend     string `json:"agent_backend"`
	BackendSessionID string `json:"backend_session_id"`
	SessionKey       string `json:"session_key"`
	SessionRoot      string `json:"session_root"`
	LastRunID        string `json:"last_run_id"`
	CreatedAt        int64  `json:"created_at"`
	UpdatedAt        int64  `json:"updated_at"`
}

func (q *Queries) UpsertTaskAgentSession(ctx context.Context, arg UpsertTaskAgentSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertTaskAgentSession,
		arg.TaskID,
		arg.AgentBackend,
		arg.BackendSessionID,
		arg.SessionKey,
		arg.SessionRoot,
		arg.LastRunID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (
  id,
  external_login,
  role,
  created_at,
  updated_at
)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  external_login = excluded.external_login,
  role = excluded.role,
  updated_at = excluded.updated_at
`

type UpsertUserParams struct {
	ID            string `json:"id"`
	ExternalLogin string `json:"external_login"`
	Role          string `json:"role"`
	CreatedAt     int64  `json:"created_at"`
	UpdatedAt     int64  `json:"updated_at"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser,
		arg.ID,
		arg.ExternalLogin,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
